"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Department = { id: number; name: string; color: string; parentId: number | null; parentName: string | null; supportEnabled: number; isActive: number; jobCount: number };
type JobTitle = { id: number; name: string; departmentId: number; department: string };
type Role = { id: number; name: string; description: string };
type Branch = { id: number; name: string; address: string; primaryPhone: string; secondaryPhone: string; email: string; socialUrl: string; isActive: number; customData: string; employeeCount: number; leadCount: number; callCount: number };
type Employee = { id: number; fullName: string; email: string; phone: string; status: "active" | "invited" | "disabled"; departmentId: number; jobTitleId: number; roleId: number; branchId: number; department: string; jobTitle: string; role: string; branchName: string };
type Field = { id: number; fieldKey: string; label: string; type: string; placeholder: string; required: number; visible: number; sortOrder: number; width: "full" | "half"; version: number; optionsJson: string };
type Lead = { id: number; fullName: string; primaryPhone: string; secondaryPhone: string; email: string; source: string; campaign: string; interest: string; status: string; priority: string; notes: string; customData: string; assignedEmployeeId: number; assignedEmployee: string; branchId: number; branchName: string; callCount: number; lastCallResult: string | null; lastCallBy: string | null; createdAt: string };
type CallRecord = { id: number; leadId: number | null; phone: string; direction: string; result: string; assignedEmployeeId: number; assignedEmployee: string; leadName: string | null; branchId: number; branchName: string; callAt: string; notes: string };
type Followup = { id: number; leadId: number; leadName: string; leadPhone: string; assignedEmployeeId: number; assignedEmployee: string; branchId: number; branchName: string; scheduledAt: string; channel: string; status: string; priority: string; notes: string; outcome: string; completedAt: string | null; createdAt: string };
type Setup = { departments: Department[]; jobTitles: JobTitle[]; roles: Role[]; employees: Employee[]; branches: Branch[]; fields: Field[]; branchFields: Field[]; leads: Lead[]; calls: CallRecord[]; followups: Followup[]; leadFields: Field[]; callFields: Field[]; leadDetailsFields: Field[]; followupFields: Field[] };
type Tab = "overview" | "departments" | "jobs" | "employees" | "leaves" | "permissions" | "forms" | "settings" | "leads" | "inboundCalls" | "followups" | "receivedFollowups" | "callCenterCalls";
type Dialog = "employee" | "department" | "job" | "field" | "branch" | "lead" | "call" | "leadDetails" | "callResult" | "leadHistory" | "scheduleFollowup" | "completeFollowup" | "rescheduleFollowup" | null;

const emptySetup: Setup = { departments: [], jobTitles: [], roles: [], employees: [], branches: [], fields: [], branchFields: [], leads: [], calls: [], followups: [], leadFields: [], callFields: [], leadDetailsFields: [], followupFields: [] };
const titles: Record<Tab, [string, string]> = {
  overview: ["إدارة الموارد البشرية", "هيكل الشركة والموظفون في مكان واحد"], departments: ["أقسام الشركة", "الأقسام الرئيسية والفرعية التي تظهر في نموذج الموظف"], jobs: ["الأدوار الوظيفية", "كل قسم وتحته الوظائف المتاحة داخله"], employees: ["الموظفون", "بيانات الموظفين وحساباتهم على النظام"], leaves: ["الإجازات", "أنواع الإجازات وسياسات الاستحقاق"], permissions: ["الصلاحيات", "صلاحيات الصفحات والإجراءات لكل مجموعة"], forms: ["مصمم النماذج", "تحكم كامل في حقول إدخال بيانات الموظف"],
  leads: ["العملاء المحتملون", "تسجيل وتوزيع الـLeads ومتابعة حالتها الأولية"], inboundCalls: ["المكالمات الواردة", "المكالمات التي استقبلها فريق خدمة العملاء"], callCenterCalls: ["مكالمات الكول سنتر", "سجل المكالمات الواردة والصادرة وربطها بالعملاء"],
  settings: ["Settings", "إدارة بيانات الفروع التي تظهر في الموظفين والعملاء والمكالمات"],
  followups: ["Leads Followup", "جدولة ومتابعة كل المواعيد القادمة مع العملاء"], receivedFollowups: ["Received Followup", "المتابعات المستحقة والمتأخرة التي تحتاج إجراءً الآن"],
};

export function CrmShell() {
  const [tab, setTab] = useState<Tab>("overview"); const [data, setData] = useState<Setup>(emptySetup); const [loading, setLoading] = useState(true); const [dialog, setDialog] = useState<Dialog>(null); const [notice, setNotice] = useState("");
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [selectedBranch, setSelectedBranch] = useState<Branch | null>(null);
  const [selectedFollowup, setSelectedFollowup] = useState<Followup | null>(null);
  async function load() { const [setupResponse, salesResponse] = await Promise.all([fetch("/api/setup", { cache: "no-store" }), fetch("/api/leads", { cache: "no-store" })]); const setup = await setupResponse.json(); const sales = await salesResponse.json(); if (!setupResponse.ok) throw new Error(setup.error || "تعذر تحميل البيانات"); if (!salesResponse.ok) throw new Error(sales.error || "تعذر تحميل العملاء"); setData({ ...setup, ...sales }); }
  useEffect(() => { load().catch((error) => setNotice(error.message)).finally(() => setLoading(false)); }, []);
  async function mutate(payload: Record<string, unknown>) { const response = await fetch("/api/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); }
  async function mutateSales(payload: Record<string, unknown>) { const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); return result; }
  const [title, subtitle] = titles[tab];
  return <main className="app-shell" dir="rtl">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">م</span><div><strong>مسار</strong><small>إدارة علاقات العملاء</small></div></div>
      <nav aria-label="التنقل الرئيسي">
        <button className={`nav-group ${tab === "overview" ? "active" : ""}`} onClick={() => setTab("overview")}><span className="nav-icon">≡</span><span><strong>إدارة الموارد البشرية</strong><small>Employees Manager</small></span><b>⌄</b></button>
        <div className="subnav">
          <SubNav label="أقسام الشركة" active={tab === "departments"} onClick={() => setTab("departments")} />
          <SubNav label="الأدوار الوظيفية" active={tab === "jobs"} onClick={() => setTab("jobs")} />
          <SubNav label="الإجازات" active={tab === "leaves"} onClick={() => setTab("leaves")} />
          <SubNav label="الموظفون" active={tab === "employees"} onClick={() => setTab("employees")} />
        </div>
        <div className="nav-separator" />
        <NavItem active={tab === "permissions"} icon="⌾" label="الصلاحيات" onClick={() => setTab("permissions")} />
        <NavItem active={tab === "forms"} icon="▤" label="مصمم النماذج" onClick={() => setTab("forms")} />
        <div className="nav-separator" />
        <button className={`nav-group sales ${["leads","inboundCalls","followups","receivedFollowups","callCenterCalls"].includes(tab) ? "active" : ""}`} onClick={() => setTab("leads")}><span className="nav-icon">▣</span><span><strong>Customer Care</strong><small>خدمة العملاء والمبيعات</small></span><b>⌄</b></button>
        <div className="subnav customer-care-menu">
          <SubNav label="Leads" active={tab === "leads"} onClick={() => setTab("leads")} />
          <SubNav label="Inbound Calls" active={tab === "inboundCalls"} onClick={() => setTab("inboundCalls")} />
          <SubNav label="Leads Followup" active={tab === "followups"} onClick={() => setTab("followups")} badge={String(data.followups.filter((followup) => followup.status === "pending").length)} />
          <SubNav label="Received Followup" active={tab === "receivedFollowups"} onClick={() => setTab("receivedFollowups")} badge={String(data.followups.filter((followup) => followup.status === "pending" && new Date(followup.scheduledAt).getTime() <= Date.now()).length)} />
          <SubNav label="Call Center Calls" active={tab === "callCenterCalls"} onClick={() => setTab("callCenterCalls")} />
          <SubNav label="Support Tickets" disabled />
          <SubNav label="Recommendation" disabled />
          <SubNav label="Chat Boxes" disabled />
        </div>
        <NavItem disabled icon="◫" label="المدفوعات" badge="المرحلة 4" /><NavItem disabled icon="◎" label="الجروبات" badge="المرحلة 5" />
        <div className="nav-separator" /><NavItem active={tab === "settings"} icon="⚙" label="Settings" onClick={() => setTab("settings")} />
      </nav>
      <div className="phase-card"><span>المرحلة الحالية</span><strong>03 — المتابعات</strong><div className="progress phase-three"><i /></div><small>جدولة المواعيد، تنبيه المستحق وحفظ النتيجة</small></div>
      <div className="profile"><span className="avatar">أم</span><div><strong>أحمد منصور</strong><small>مدير النظام</small></div><button>•••</button></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">مسار CRM <b>/</b> {["leads","inboundCalls","followups","receivedFollowups","callCenterCalls"].includes(tab) ? "Customer Care" : tab === "settings" ? "Settings" : "الموارد البشرية"}</span><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div><div className="top-actions"><button className="icon-button">♢<i /></button>{tab === "departments" && <button className="primary" onClick={() => setDialog("department")}>＋ إضافة قسم</button>}{tab === "jobs" && <button className="primary" onClick={() => setDialog("job")}>＋ إضافة وظيفة</button>}{tab === "employees" && <button className="primary" onClick={() => setDialog("employee")}>＋ إضافة موظف</button>}{tab === "forms" && <button className="primary" onClick={() => setDialog("field")}>＋ إضافة حقل</button>}{tab === "settings" && <button className="primary" onClick={() => { setSelectedBranch(null); setDialog("branch"); }}>＋ إضافة فرع</button>}{tab === "leads" && <button className="primary" onClick={() => setDialog("lead")}>＋ تسجيل Lead</button>}{(tab === "inboundCalls" || tab === "callCenterCalls") && <button className="primary" onClick={() => setDialog("call")}>＋ تسجيل مكالمة</button>}</div></header>
      {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {loading ? <Loading /> : <Page tab={tab} data={data} mutate={mutate} open={setDialog} setNotice={setNotice} selectLead={(lead, next) => { setSelectedLead(lead); setDialog(next); }} selectFollowup={(followup, next) => { setSelectedFollowup(followup); setDialog(next); }} editBranch={(branch) => { setSelectedBranch(branch); setDialog("branch"); }} />}
    </section>
    {dialog === "employee" && <EmployeeDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createEmployee", ...payload }); setDialog(null); setNotice("تم إنشاء حساب الموظف وإضافة ملفه بنجاح"); }} />}
    {dialog === "department" && <DepartmentDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createDepartment", ...payload }); setDialog(null); setNotice("تمت إضافة القسم وسيظهر الآن في نموذج الموظف"); }} />}
    {dialog === "job" && <JobDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createJobTitle", ...payload }); setDialog(null); setNotice("تمت إضافة الوظيفة تحت القسم المحدد"); }} />}
    {dialog === "field" && <FieldDialog onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "addField", ...payload }); setDialog(null); setNotice("تمت إضافة الحقل للنموذج المحدد"); }} />}
    {dialog === "branch" && <BranchDialog data={data} branch={selectedBranch} onClose={() => setDialog(null)} onSubmit={async (payload) => { const standard=new Set(["name","address","primaryPhone","secondaryPhone","email","socialUrl","isActive"]); let existing:Record<string,unknown>={}; try{existing=selectedBranch?JSON.parse(selectedBranch.customData||"{}"):{};}catch{existing={};} const customData={...existing,...Object.fromEntries(Object.entries(payload).filter(([key])=>!standard.has(key)))}; await mutate({ action: selectedBranch ? "updateBranch" : "createBranch", id: selectedBranch?.id, ...payload, customData }); setDialog(null); setNotice(selectedBranch ? "تم تحديث بيانات الفرع في كل أجزاء النظام" : "تمت إضافة الفرع وأصبح متاحًا في النماذج"); }} />}
    {dialog === "lead" && <LeadDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "createLead", ...payload }); setDialog(null); setNotice("تم تسجيل العميل المحتمل وتعيين الموظف المسؤول"); }} />}
    {dialog === "call" && <CallDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { const result = await mutateSales({ action: "createCall", ...payload }); setDialog(null); setNotice(result.matchedLead ? "تم تسجيل المكالمة وربطها بالعميل الموجود" : "تم تسجيل المكالمة كرقم غير مرتبط بعميل"); }} />}
    {dialog === "leadDetails" && selectedLead && <LeadDetailsDialog lead={selectedLead} fields={data.leadDetailsFields} data={data} onClose={() => setDialog(null)} onSubmit={async (details) => { await mutateSales({ action: "updateLeadDetails", id: selectedLead.id, details }); setDialog(null); setNotice("تم استكمال بيانات العميل"); }} />}
    {dialog === "callResult" && selectedLead && <LeadCallResultDialog lead={selectedLead} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "recordLeadCallResult", id: selectedLead.id, ...payload }); setDialog(null); setNotice("تم حفظ نتيجة المكالمة وإضافتها إلى السجل"); }} />}
    {dialog === "leadHistory" && selectedLead && <LeadHistoryDialog lead={selectedLead} calls={data.calls.filter((call) => call.leadId === selectedLead.id)} onClose={() => setDialog(null)} />}
    {dialog === "scheduleFollowup" && selectedLead && <FollowupDialog lead={selectedLead} data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "createFollowup", leadId: selectedLead.id, ...payload }); setDialog(null); setNotice("تمت جدولة المتابعة وإضافتها لقائمة المسؤول"); }} />}
    {dialog === "completeFollowup" && selectedFollowup && <CompleteFollowupDialog followup={selectedFollowup} onClose={() => setDialog(null)} onSubmit={async (outcome) => { await mutateSales({ action: "completeFollowup", id: selectedFollowup.id, outcome }); setDialog(null); setNotice("تم إنهاء المتابعة وحفظ نتيجتها"); }} />}
    {dialog === "rescheduleFollowup" && selectedFollowup && <RescheduleDialog followup={selectedFollowup} onClose={() => setDialog(null)} onSubmit={async (scheduledAt) => { await mutateSales({ action: "rescheduleFollowup", id: selectedFollowup.id, scheduledAt }); setDialog(null); setNotice("تم تعديل موعد المتابعة"); }} />}
  </main>;
}

function Page({ tab, data, mutate, open, setNotice, selectLead, selectFollowup, editBranch }: { tab: Tab; data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; open: (d: Dialog) => void; setNotice: (s: string) => void; selectLead: (lead: Lead, dialog: Dialog) => void; selectFollowup: (followup: Followup, dialog: Dialog) => void; editBranch: (branch: Branch) => void }) {
  if (tab === "overview") return <HrOverview data={data} go={open} />;
  if (tab === "departments") return <Departments data={data} add={() => open("department")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "jobs") return <Jobs data={data} add={() => open("job")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "employees") return <Employees data={data} add={() => open("employee")} />;
  if (tab === "leaves") return <Leaves />;
  if (tab === "permissions") return <Permissions roles={data.roles} />;
  if (tab === "settings") return <SettingsPage data={data} add={() => open("branch")} edit={editBranch} mutate={mutate} setNotice={setNotice} />;
  if (tab === "leads") return <LeadsPage data={data} addLead={() => open("lead")} addCall={() => open("call")} onAction={selectLead} />;
  if (tab === "inboundCalls") return <CallsPage data={data} add={() => open("call")} mode="incoming" />;
  if (tab === "followups") return <FollowupsPage data={data} mode="all" onAction={selectFollowup} />;
  if (tab === "receivedFollowups") return <FollowupsPage data={data} mode="due" onAction={selectFollowup} />;
  if (tab === "callCenterCalls") return <CallsPage data={data} add={() => open("call")} mode="all" />;
  return <FormBuilder fields={data.fields} data={data} mutate={mutate} onAdd={() => open("field")} />;
}

function SubNav({ label, active=false, disabled=false, badge, onClick }: { label: string; active?: boolean; disabled?: boolean; badge?: string; onClick?: () => void }) { return <button className={`${active ? "active" : ""} ${disabled ? "disabled" : ""}`} onClick={onClick} disabled={disabled}><i /><span>{label}</span>{badge && <em>{badge}</em>}</button>; }
function NavItem({ active, disabled, icon, label, badge, onClick }: { active?: boolean; disabled?: boolean; icon: string; label: string; badge?: string; onClick?: () => void }) { return <button className={`nav-item ${active ? "active" : ""} ${disabled ? "disabled" : ""}`} onClick={onClick} disabled={disabled}><span className="nav-icon">{icon}</span><span>{label}</span>{badge && <em>{badge}</em>}</button>; }
function Loading() { return <div className="loading-grid"><div /><div /><div /><article /></div>; }

function HrOverview({ data, go }: { data: Setup; go: (d: Dialog) => void }) {
  return <div className="content-stack"><section className="metrics"><Metric label="الموظفون" value={data.employees.length} hint="ملفات مسجلة" tone="green" /><Metric label="أقسام الشركة" value={data.departments.length} hint="رئيسية وفرعية" tone="blue" /><Metric label="الأدوار الوظيفية" value={data.jobTitles.length} hint="مرتبطة بالأقسام" tone="orange" /><Metric label="حسابات نشطة" value={data.employees.filter((e) => e.status === "active").length} hint="تعمل على النظام" tone="purple" /></section><section className="hr-map"><div className="hr-intro"><span>نظام موارد بشرية مترابط</span><h2>ابدأ بالهيكل، ثم أضف فريقك</h2><p>القسم يحدد الوظائف المتاحة، والوظيفة ومجموعة الصلاحيات تحددان ما يمكن للموظف رؤيته وتنفيذه داخل النظام.</p></div><div className="flow-cards"><FlowCard n="01" title="أقسام الشركة" text="أضف الأقسام الرئيسية والفرعية" /><b>←</b><FlowCard n="02" title="الأدوار الوظيفية" text="عرّف الوظائف داخل كل قسم" /><b>←</b><FlowCard n="03" title="الموظفون" text="أنشئ الملف والحساب والصلاحيات" /></div><div className="quick-row"><button onClick={() => go("department")}>＋ قسم جديد</button><button onClick={() => go("job")}>＋ وظيفة جديدة</button><button onClick={() => go("employee")}>＋ موظف جديد</button></div></section></div>;
}
function FlowCard({ n, title, text }: { n: string; title: string; text: string }) { return <article><span>{n}</span><strong>{title}</strong><small>{text}</small></article>; }

function Departments({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteDepartment", id }); setNotice("تم حذف القسم"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <section className="panel"><div className="panel-head"><div><h2>قائمة أقسام الشركة</h2><p>الأقسام هنا هي المصدر المباشر لقائمة القسم داخل نموذج الموظف.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث عن قسم..." /></label><button className="secondary" onClick={add}>＋ إضافة جديد</button></div></div><div className="table-wrap"><table className="departments-table"><thead><tr><th>#</th><th>اسم القسم</th><th>القسم الرئيسي</th><th>الدعم</th><th>عدد الوظائف</th><th>الإجراءات</th></tr></thead><tbody>{data.departments.map((d, i) => <tr key={d.id}><td>{i + 1}</td><td><strong className="dept-title"><i style={{ background: d.color }} />{d.name}</strong></td><td>{d.parentName ? <span>{d.parentName}</span> : <span className="tag no-parent">بدون قسم رئيسي</span>}</td><td>{d.supportEnabled ? <span className="tag support">مفعّل</span> : <span className="tag off">غير مفعّل</span>}</td><td><span className="count-chip">{d.jobCount} وظائف</span></td><td><div className="actions"><button className="edit">تعديل</button><button className="delete" onClick={() => remove(d.id)}>حذف</button></div></td></tr>)}</tbody></table></div></section>;
}

function Jobs({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteJobTitle", id }); setNotice("تم حذف الوظيفة"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <div className="jobs-layout"><div className="jobs-toolbar"><p>كل وظيفة مرتبطة بقسم واحد، وتظهر للموظف بعد اختيار القسم.</p><button className="secondary" onClick={add}>＋ إضافة وظيفة</button></div><div className="department-groups">{data.departments.map((department) => { const jobs = data.jobTitles.filter((job) => job.departmentId === department.id); return <section className="job-group" key={department.id}><header><span style={{ background: department.color }}>{initials(department.name)}</span><div><h2>{department.name}</h2><p>{jobs.length} أدوار وظيفية</p></div><button onClick={add}>＋</button></header><div>{jobs.length ? jobs.map((job) => <article key={job.id}><div><strong>{job.name}</strong><small>يتبع قسم {department.name}</small></div><button className="row-menu">تعديل</button><button className="row-menu danger" onClick={() => remove(job.id)}>حذف</button></article>) : <p className="empty-line">لا توجد وظائف داخل هذا القسم بعد.</p>}</div></section>; })}</div></div>;
}

function SettingsPage({ data, add, edit, mutate, setNotice }: { data: Setup; add: () => void; edit: (branch: Branch) => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(branch: Branch) { try { await mutate({ action: "deleteBranch", id: branch.id }); setNotice("تم حذف الفرع"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر حذف الفرع"); } }
  const active = data.branches.filter((branch) => branch.isActive).length;
  return <div className="content-stack settings-page"><section className="metrics"><Metric label="إجمالي الفروع" value={data.branches.length} hint="فروع مسجلة" tone="green" /><Metric label="الفروع النشطة" value={active} hint="متاحة في النماذج" tone="blue" /><Metric label="الموظفون المرتبطون" value={data.branches.reduce((sum, branch) => sum + Number(branch.employeeCount), 0)} hint="حسب الفرع" tone="orange" /><Metric label="العملاء والمكالمات" value={data.branches.reduce((sum, branch) => sum + Number(branch.leadCount) + Number(branch.callCount), 0)} hint="مرتبطة بالفروع" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>بيانات الفروع</h2><p>أي تعديل هنا يظهر تلقائيًا في نموذج الموظف والـLead والمكالمة.</p></div><button className="secondary" onClick={add}>＋ إضافة فرع</button></div>{data.branches.length ? <div className="branch-grid">{data.branches.map((branch) => <article className="branch-card" key={branch.id}><header><span className="branch-icon">⌂</span><div><h3>{branch.name}</h3><span className={`branch-state ${branch.isActive ? "active" : "inactive"}`}>{branch.isActive ? "نشط" : "غير نشط"}</span></div><div className="branch-actions"><button onClick={() => edit(branch)}>تعديل</button><button className="danger" onClick={() => remove(branch)}>حذف</button></div></header><p className="branch-address">⌖ {branch.address}</p><div className="branch-contact"><a href={`tel:${branch.primaryPhone}`}>☎ {branch.primaryPhone}</a>{branch.secondaryPhone && <a href={`tel:${branch.secondaryPhone}`}>☎ {branch.secondaryPhone}</a>}{branch.email && <a href={`mailto:${branch.email}`}>✉ {branch.email}</a>}{branch.socialUrl && <a href={branch.socialUrl} target="_blank" rel="noreferrer">↗ صفحة التواصل</a>}</div><footer><span><b>{branch.employeeCount}</b> موظف</span><span><b>{branch.leadCount}</b> Lead</span><span><b>{branch.callCount}</b> مكالمة</span></footer></article>)}</div> : <div className="empty"><span>⌂</span><h3>لا توجد فروع</h3><p>أضف أول فرع ليظهر في كل نماذج النظام.</p><button className="primary" onClick={add}>＋ إضافة فرع</button></div>}</section></div>;
}

function Employees({ data, add }: { data: Setup; add: () => void }) {
  const active = data.employees.filter((e) => e.status === "active").length;
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي الموظفين" value={data.employees.length} hint="كل الملفات" tone="green" /><Metric label="الحسابات النشطة" value={active} hint="جاهزة للعمل" tone="blue" /><Metric label="دعوات معلقة" value={data.employees.filter((e) => e.status === "invited").length} hint="في انتظار التفعيل" tone="orange" /><Metric label="الأقسام" value={data.departments.length} hint="هيكل الشركة" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>دليل الموظفين</h2><p>ملف الموظف، الفرع، القسم، الدور الوظيفي، وصلاحيات النظام.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو البريد..." /></label><button className="secondary" onClick={add}>＋ موظف جديد</button></div></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>الفرع</th><th>القسم</th><th>الدور الوظيفي</th><th>الصلاحيات</th><th>الحالة</th><th /></tr></thead><tbody>{data.employees.map((e) => <tr key={e.id}><td><div className="employee"><span>{initials(e.fullName)}</span><div><strong>{e.fullName}</strong><small>{e.email}</small></div></div></td><td>{e.branchName || "—"}</td><td><span className="department-dot" style={{ background: data.departments.find((d) => d.id === e.departmentId)?.color }} />{e.department}</td><td>{e.jobTitle}</td><td><span className="role-chip">{e.role}</span></td><td><Status status={e.status} /></td><td><button className="row-menu">•••</button></td></tr>)}</tbody></table></div><div className="table-footer"><span>عرض {data.employees.length} موظفين</span><button className="primary" onClick={add}>＋ إضافة موظف</button></div></section></div>;
}

function Leaves() { return <section className="panel leaves-panel"><div className="panel-head"><div><h2>أنواع الإجازات</h2><p>الجزء ظاهر داخل الموارد البشرية، وسيتم تفعيل سياساته عند اعتماد متطلبات الإجازات.</p></div><span className="tag support">مخطط</span></div><div className="leave-grid"><article><span>سنوية</span><strong>21 يوم</strong><small>الرصيد الافتراضي</small></article><article><span>عارضة</span><strong>6 أيام</strong><small>ضمن الرصيد السنوي</small></article><article><span>مرضية</span><strong>حسب اللائحة</strong><small>تحتاج مستندًا</small></article></div><div className="guard-note"><span>◈</span><div><strong>لم يتم تفعيل عمليات الإجازات بعد</strong><p>سنحدد دورة الطلب والموافقة والأرصدة في خطوة مستقلة حتى لا نفترض سياسة غير معتمدة.</p></div></div></section>; }

function Permissions({ roles }: { roles: Role[] }) { const rows = ["الموظفون", "الأقسام والوظائف", "إعدادات النماذج", "العملاء المحتملون"]; return <div className="split-layout"><section className="panel roles-list"><div className="panel-head"><div><h2>مجموعات الصلاحيات</h2><p>صلاحيات استخدام النظام، وليست الدور الوظيفي.</p></div><button className="secondary">＋ مجموعة جديدة</button></div>{roles.map((role, i) => <button key={role.id} className={`role-row ${i === 0 ? "selected" : ""}`}><span className="role-symbol">{i === 0 ? "♛" : "◆"}</span><div><strong>{role.name}</strong><small>{role.description}</small></div></button>)}</section><section className="panel permission-matrix"><div className="panel-head"><div><span className="mini-label">صلاحيات المجموعة</span><h2>مدير النظام</h2></div><button className="primary">حفظ التغييرات</button></div><table><thead><tr><th>الصفحة</th><th>عرض</th><th>إضافة</th><th>تعديل</th><th>حذف</th></tr></thead><tbody>{rows.map((row, ri) => <tr key={row}><td><strong>{row}</strong></td>{[0,1,2,3].map((c) => <td key={c}><label className="check"><input type="checkbox" defaultChecked={ri < 3 || c < 2} /><span>✓</span></label></td>)}</tr>)}</tbody></table></section></div>; }

function FormBuilder({ fields: initialFields, data, mutate, onAdd }: { fields: Field[]; data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; onAdd: () => void }) {
  const formOptions=[{key:"employee",name:"الموظف",fields:initialFields},{key:"branch",name:"الفرع",fields:data.branchFields},{key:"lead",name:"Lead جديدة",fields:data.leadFields},{key:"call",name:"المكالمة",fields:data.callFields},{key:"lead_details",name:"استكمال العميل",fields:data.leadDetailsFields},{key:"followup",name:"المتابعة",fields:data.followupFields}];
  const [formKey,setFormKey]=useState("employee"); const [saving, setSaving] = useState<number | null>(null); const selected=formOptions.find((form)=>form.key===formKey)||formOptions[0]; const fields=selected.fields; const previewFields=fields.filter((f)=>f.visible).slice(0,8);
  return <div className="builder-layout"><section className="panel field-panel"><div className="panel-head"><div><span className="version">نسخة {fields[0]?.version ?? 1}</span><h2>نموذج {selected.name}</h2><p>{fields.length} حقلًا قابلًا للتحكم من هنا.</p></div><div className="form-builder-actions"><select value={formKey} onChange={(e)=>setFormKey(e.target.value)}>{formOptions.map((form)=><option key={form.key} value={form.key}>{form.name}</option>)}</select><button className="secondary" onClick={onAdd}>＋ حقل جديد</button></div></div><div className="field-list">{fields.map((f, i) => <div className={`field-row ${!f.visible ? "muted" : ""}`} key={f.id}><span className="drag">⠿</span><span className="field-index">{String(i + 1).padStart(2,"0")}</span><div className="field-info"><strong>{f.label}</strong><small>{f.fieldKey} · {f.type}</small></div><label className="mini-toggle"><input type="checkbox" checked={!!f.required} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:!!f.visible, required:e.target.checked }); setSaving(null); }} /><span />إلزامي</label><label className="mini-toggle"><input type="checkbox" checked={!!f.visible} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:e.target.checked, required:!!f.required }); setSaving(null); }} /><span />ظاهر</label><button className="row-menu">{saving === f.id ? "…" : "•••"}</button></div>)}</div></section><section className="panel preview-panel"><div className="preview-head"><div><span className="live-dot" />معاينة مباشرة</div><span>{selected.name}</span></div><div className="form-preview"><div className="preview-title"><span>＋</span><div><h3>نموذج {selected.name}</h3><p>المعاينة تتغير فورًا مع إعدادات الحقول.</p></div></div><div className="dynamic-grid">{previewFields.map((f) => <DynamicField key={f.id} field={f} value="" setValue={() => {}} data={data} values={{}} disabled />)}</div></div></section></div>;
}

function LeadsPage({ data, addLead, addCall, onAction }: { data: Setup; addLead: () => void; addCall: () => void; onAction: (lead: Lead, dialog: Dialog) => void }) {
  const newCount = data.leads.filter((lead) => lead.status === "new").length;
  const urgent = data.leads.filter((lead) => lead.priority === "urgent").length;
  return <div className="content-stack lead-board">
    <section className="metrics"><Metric label="إجمالي الـLeads" value={data.leads.length} hint="عملاء محتملون" tone="green" /><Metric label="جديدة" value={newCount} hint="لم تبدأ المتابعة" tone="blue" /><Metric label="أولوية عاجلة" value={urgent} hint="تحتاج تصرفًا سريعًا" tone="orange" /><Metric label="المكالمات" value={data.calls.length} hint="مسجلة في المرحلة" tone="purple" /></section>
    <section className="panel"><div className="panel-head"><div><h2>قائمة العملاء المحتملين</h2><p>رقم الهاتف فريد، وأي محاولة لتسجيله مرة أخرى ستظهر العميل الموجود.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو الهاتف..." /></label><button className="secondary" onClick={addCall}>☎ مكالمة جديدة</button><button className="primary" onClick={addLead}>＋ Lead جديدة</button></div></div>
      {data.leads.length ? <div className="table-wrap"><table><thead><tr><th>العميل</th><th>الفرع</th><th>المصدر</th><th>الكورس</th><th>النتيجة</th><th>آخر مكالمة بواسطة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{data.leads.map((lead) => <tr key={lead.id}><td><div className="employee lead-person"><span>{initials(lead.fullName)}</span><div><strong>{lead.fullName}</strong><small>{lead.primaryPhone}</small></div></div></td><td>{lead.branchName || "—"}</td><td><span className="source-chip">{lead.source}</span></td><td>{lead.interest || "—"}</td><td><CallResult value={lead.lastCallResult || "no_answer"} /></td><td>{lead.lastCallBy || lead.assignedEmployee || "—"}</td><td><LeadStatus value={lead.status} /></td><td><div className="lead-actions"><button className="followup" onClick={() => onAction(lead, "scheduleFollowup")} title="جدولة متابعة">◷</button><button className="complete" onClick={() => onAction(lead, "leadDetails")} title="استكمال بيانات العميل">✎</button><button className="result" onClick={() => onAction(lead, "callResult")} title="تسجيل نتيجة المكالمة">?</button><button className="history" onClick={() => onAction(lead, "leadHistory")} title="سجل المكالمات">☷</button></div></td></tr>)}</tbody></table></div> : <div className="empty"><span>◇</span><h3>لا توجد Leads حتى الآن</h3><p>سجل أول عميل محتمل وحدد مصدره والموظف المسؤول.</p><button className="primary" onClick={addLead}>＋ تسجيل Lead جديدة</button></div>}
      <div className="table-footer"><span>إجمالي {data.leads.length} عميل محتمل</span><span className="duplicate-guard">✓ منع تكرار الهاتف مفعّل</span></div>
    </section>
  </div>;
}

function CallsPage({ data, add, mode }: { data: Setup; add: () => void; mode: "incoming" | "all" }) {
  const calls = mode === "incoming" ? data.calls.filter((call) => call.direction === "incoming") : data.calls;
  const answered = calls.filter((call) => call.result === "answered").length;
  const linked = calls.filter((call) => call.leadId).length;
  const heading = mode === "incoming" ? "Inbound Calls" : "Call Center Calls";
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي المكالمات" value={calls.length} hint={mode === "incoming" ? "مكالمات واردة" : "كل المكالمات المسجلة"} tone="green" /><Metric label="تم الرد" value={answered} hint="مكالمات مكتملة" tone="blue" /><Metric label="مرتبطة بعميل" value={linked} hint="تم التعرف على الرقم" tone="orange" /><Metric label="أرقام جديدة" value={calls.length - linked} hint="غير مرتبطة بـLead" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>{heading}</h2><p>يتم البحث عن رقم الهاتف وربطه تلقائيًا بعميل موجود.</p></div><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>{calls.length ? <div className="table-wrap"><table><thead><tr><th>العميل / الرقم</th><th>الفرع</th><th>نوع المكالمة</th><th>النتيجة</th><th>الموظف المسؤول</th><th>التوقيت</th><th>الملاحظات</th></tr></thead><tbody>{calls.map((call) => <tr key={call.id}><td><div className="call-identity"><strong>{call.leadName || "رقم غير مسجل"}</strong><small>{call.phone}</small></div></td><td>{call.branchName || "—"}</td><td><span className={`direction ${call.direction}`}>{call.direction === "incoming" ? "↙ واردة" : "↗ صادرة"}</span></td><td><CallResult value={call.result} /></td><td>{call.assignedEmployee || "غير معيّن"}</td><td>{formatDate(call.callAt)}</td><td className="notes-cell">{call.notes || "—"}</td></tr>)}</tbody></table></div> : <div className="empty"><span>☎</span><h3>{mode === "incoming" ? "لا توجد مكالمات واردة" : "لا توجد مكالمات مسجلة"}</h3><p>سجل مكالمة جديدة، وسيتم ربطها بالـLead تلقائيًا.</p><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>}</section></div>;
}

function FollowupsPage({ data, mode, onAction }: { data: Setup; mode: "all" | "due"; onAction: (followup: Followup, dialog: Dialog) => void }) {
  const now = Date.now();
  const todayEnd = new Date(); todayEnd.setHours(23,59,59,999);
  const pending = data.followups.filter((followup) => followup.status === "pending");
  const rows = mode === "due" ? pending.filter((followup) => new Date(followup.scheduledAt).getTime() <= todayEnd.getTime()) : data.followups;
  const overdue = pending.filter((followup) => new Date(followup.scheduledAt).getTime() < now).length;
  const today = pending.filter((followup) => { const time=new Date(followup.scheduledAt); const date=new Date(); return time.toDateString()===date.toDateString(); }).length;
  const completed = data.followups.filter((followup) => followup.status === "completed").length;
  return <div className="content-stack followup-board"><section className="metrics"><Metric label="متابعات مفتوحة" value={pending.length} hint="في انتظار الإجراء" tone="green" /><Metric label="مستحقة اليوم" value={today} hint="ضمن خطة اليوم" tone="blue" /><Metric label="متأخرة" value={overdue} hint="تحتاج إجراءً سريعًا" tone="orange" /><Metric label="مكتملة" value={completed} hint="تم حفظ نتيجتها" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>{mode === "due" ? "المتابعات الواردة والمستحقة" : "جدول متابعات الـLeads"}</h2><p>{mode === "due" ? "المواعيد المتأخرة والمستحقة حتى نهاية اليوم." : "كل المتابعات القادمة والمكتملة مرتبة حسب الموعد."}</p></div><span className="followup-live"><i /> تحديث تلقائي حسب الوقت</span></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>العميل</th><th>الموعد</th><th>التوقيت</th><th>الوسيلة</th><th>المسؤول</th><th>الفرع</th><th>الأولوية</th><th>الملاحظات / النتيجة</th><th>الإجراء</th></tr></thead><tbody>{rows.map((followup)=><tr key={followup.id} className={followupTiming(followup)==="overdue"?"overdue-row":""}><td><div className="call-identity"><strong>{followup.leadName}</strong><small>{followup.leadPhone}</small></div></td><td>{formatDate(followup.scheduledAt)}</td><td><FollowupTiming followup={followup}/></td><td><span className="channel-chip">{followupChannel(followup.channel)}</span></td><td>{followup.assignedEmployee||"غير معيّن"}</td><td>{followup.branchName||"—"}</td><td><Priority value={followup.priority}/></td><td className="notes-cell">{followup.status==="completed"?followup.outcome:followup.notes}</td><td>{followup.status==="pending"?<div className="followup-actions"><button className="done" onClick={()=>onAction(followup,"completeFollowup")}>✓ إنهاء</button><button onClick={()=>onAction(followup,"rescheduleFollowup")}>◷ تأجيل</button></div>:<span className="tag support">مكتملة</span>}</td></tr>)}</tbody></table></div>:<div className="empty"><span>◷</span><h3>{mode==="due"?"لا توجد متابعات مستحقة":"لا توجد متابعات حتى الآن"}</h3><p>{mode==="due"?"كل المواعيد الحالية تمت متابعتها.":"يمكن جدولة متابعة من زر الساعة داخل قائمة الـLeads."}</p></div>}</section></div>;
}

function followupTiming(followup: Followup) { if(followup.status==="completed") return "completed"; const due=new Date(followup.scheduledAt).getTime(); const now=Date.now(); if(due<now) return "overdue"; if(due-now<24*60*60*1000) return "today"; return "upcoming"; }
function FollowupTiming({followup}:{followup:Followup}) { const value=followupTiming(followup); const labels:Record<string,string>={completed:"تمت",overdue:"متأخرة",today:"خلال 24 ساعة",upcoming:"قادمة"}; return <span className={`followup-timing ${value}`}><i/>{labels[value]}</span>; }
function followupChannel(value:string) { return ({call:"مكالمة",whatsapp:"واتساب",message:"رسالة",visit:"زيارة",online_meeting:"اجتماع أونلاين"} as Record<string,string>)[value]||value; }

function Priority({ value }: { value: string }) { const labels: Record<string,string> = { normal:"عادية", high:"مرتفعة", urgent:"عاجلة" }; return <span className={`priority ${value}`}>{labels[value] || value}</span>; }
function LeadStatus({ value }: { value: string }) { const labels: Record<string,string> = { new:"جديدة", contacted:"تم التواصل", qualified:"مؤهلة", unqualified:"غير مؤهلة", followup:"متابعة" }; return <span className={`lead-status ${value}`}><i />{labels[value] || value}</span>; }
function CallResult({ value }: { value: string }) { const labels: Record<string,string> = { answered:"تم الرد", no_answer:"لم يرد", interested:"مهتم", not_interested:"غير مهتم", busy:"مشغول", wrong_number:"رقم خاطئ", callback:"معاودة الاتصال" }; return <span className={`call-result ${value}`}>{labels[value] || value}</span>; }
function formatDate(value: string) { try { return new Intl.DateTimeFormat("ar-EG", { dateStyle:"short", timeStyle:"short" }).format(new Date(value)); } catch { return value; } }

function LeadDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const [values,setValues]=useState<Record<string,unknown>>({}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.leadFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","primaryPhone","secondaryPhone","source","course","branchId","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,assignedEmployeeId:data.employees.find((employee)=>employee.status==="active")?.id,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل العميل");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◇</span><div><h2>تسجيل Lead جديدة</h2><p>بيانات العميل ومصدره والموظف المسؤول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error duplicate-error">{error}</p>}<div className="employee-form-note"><span>✓</span><p>سيتم تنظيف رقم الهاتف ومراجعته لمنع تسجيل نفس العميل مرتين.</p></div><div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التحقق والحفظ...":"تسجيل العميل"}</button></div></form></div>;
}

function CallDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const now=new Date(); now.setMinutes(now.getMinutes()-now.getTimezoneOffset()); const [values,setValues]=useState<Record<string,unknown>>({direction:"صادرة",result:"تم الرد",callAt:now.toISOString().slice(0,16)}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.callFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["phone","direction","result","assignedEmployeeId","branchId","callAt","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل المكالمة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog compact-sales" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">☎</span><div><h2>تسجيل مكالمة جديدة</h2><p>لو الرقم مسجل سيتم ربط المكالمة بالعميل تلقائيًا.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التسجيل...":"حفظ المكالمة"}</button></div></form></div>;
}

function FollowupDialog({ lead, data, onClose, onSubmit }: { lead: Lead; data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const next=new Date(Date.now()+60*60*1000); next.setMinutes(next.getMinutes()-next.getTimezoneOffset());
  const [values,setValues]=useState<Record<string,unknown>>({scheduledAt:next.toISOString().slice(0,16),assignedEmployeeId:lead.assignedEmployeeId||data.employees.find((employee)=>employee.status==="active")?.id,channel:"مكالمة",priority:"عادية"}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر جدولة المتابعة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog compact-sales" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◷</span><div><h2>جدولة متابعة جديدة</h2><p>{lead.fullName} · {lead.primaryPhone}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>النموذج ديناميكي، والموعد سيظهر تلقائيًا في قائمة المسؤول والمتابعات المستحقة.</p></div><div className="dynamic-grid dialog-fields">{data.followupFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الجدولة...":"حفظ موعد المتابعة"}</button></div></form></div>;
}

function CompleteFollowupDialog({followup,onClose,onSubmit}:{followup:Followup;onClose:()=>void;onSubmit:(outcome:string)=>Promise<void>}) { const [outcome,setOutcome]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(outcome)}catch(err){setError(err instanceof Error?err.message:"تعذر إنهاء المتابعة");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">✓</span><div><h2>إنهاء المتابعة</h2><p>{followup.leadName} · {followupChannel(followup.channel)}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields"><label className="full"><span>نتيجة المتابعة *</span><textarea required value={outcome} onChange={(e)=>setOutcome(e.target.value)} placeholder="ماذا حدث؟ وما هي الخطوة التالية؟"/></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"إنهاء وحفظ النتيجة"}</button></div></form></div>; }

function RescheduleDialog({followup,onClose,onSubmit}:{followup:Followup;onClose:()=>void;onSubmit:(scheduledAt:string)=>Promise<void>}) { const initial=new Date(followup.scheduledAt); initial.setMinutes(initial.getMinutes()-initial.getTimezoneOffset()); const [scheduledAt,setScheduledAt]=useState(initial.toISOString().slice(0,16)); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(scheduledAt)}catch(err){setError(err instanceof Error?err.message:"تعذر تعديل الموعد");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◷</span><div><h2>تعديل موعد المتابعة</h2><p>{followup.leadName}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields"><label className="full"><span>الموعد الجديد *</span><input type="datetime-local" required value={scheduledAt} onChange={(e)=>setScheduledAt(e.target.value)}/></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ الموعد الجديد"}</button></div></form></div>; }

function leadCustomData(lead: Lead) { try { return JSON.parse(lead.customData || "{}") as Record<string, unknown>; } catch { return {}; } }

function LeadDetailsDialog({ lead, fields, data, onClose, onSubmit }: { lead: Lead; fields: Field[]; data: Setup; onClose: () => void; onSubmit: (details: Record<string,unknown>) => Promise<void> }) {
  const [values,setValues]=useState<Record<string,unknown>>({ ...leadCustomData(lead), course:lead.interest, source:lead.source }); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ البيانات");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog details-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">✎</span><div><h2>استكمال بيانات العميل</h2><p>بيانات البيع والتصنيف الخاصة بـ {lead.fullName}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="lead-fixed-fields"><label><span>الاسم</span><input value={lead.fullName} disabled /></label><label><span>رقم الموبايل</span><input value={lead.primaryPhone} disabled /></label><label><span>رقم الموبايل 2</span><input value={lead.secondaryPhone || "—"} disabled /></label></div><div className="dynamic-grid dialog-fields">{fields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إغلاق</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ باقي البيانات"}</button></div></form></div>;
}

function LeadCallResultDialog({ lead, onClose, onSubmit }: { lead: Lead; onClose: () => void; onSubmit: (payload: Record<string,unknown>) => Promise<void> }) {
  const [result,setResult]=useState("No Answer"); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit({result,notes})}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ النتيجة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact call-result-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">☎</span><div><h2>نتيجة المكالمة</h2><p>تسجيل نتيجة اتصال فريق المبيعات</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="lead-fixed-fields stacked"><label><span>الاسم</span><input value={lead.fullName} disabled /></label><label><span>رقم الموبايل</span><input value={lead.primaryPhone} disabled /></label><label><span>رقم الموبايل 2</span><input value={lead.secondaryPhone || "—"} disabled /></label></div><div className="dynamic-grid dialog-fields result-fields"><label className="full"><span>نتيجة المكالمة *</span><select value={result} onChange={(e)=>setResult(e.target.value)} required><option>No Answer</option><option>Answered</option><option>Interested</option><option>Not Interested</option><option>Busy</option><option>Wrong Number</option><option>Call Back</option></select></label><label className="full"><span>ملاحظات</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="اكتب ملخص المكالمة" /></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إغلاق</button><button className="primary warning" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ النتيجة"}</button></div></form></div>;
}

function LeadHistoryDialog({ lead, calls, onClose }: { lead: Lead; calls: CallRecord[]; onClose: () => void }) {
  const details=leadCustomData(lead); const detailRows=[["الاسم",lead.fullName],["موبايل 1",lead.primaryPhone],["موبايل 2",lead.secondaryPhone||"—"],["النوع",String(details.gender||"—")],["العمر",String(details.age||"—")],["الموقع",String(details.location||"—")],["الفرع",lead.branchName||"—"],["الكورس",lead.interest||"—"],["الشريحة",String(details.segment||"—")],["الوظيفة",String(details.job||"—")],["العرض",String(details.offer||"—")]];
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="dialog history-dialog"><div className="dialog-head"><div><span className="dialog-icon">◉</span><div><h2>سجل العميل [{lead.primaryPhone}]</h2><p>البيانات الكاملة وكل المكالمات المسجلة</p></div></div><button onClick={onClose}>×</button></div><div className="history-summary">{detailRows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="history-section"><h3>سجل المكالمات</h3>{calls.length?<div className="table-wrap"><table><thead><tr><th>النتيجة</th><th>المرحلة</th><th>وقت الإجراء</th><th>الملاحظات</th><th>الموظف</th></tr></thead><tbody>{calls.map((call)=><tr key={call.id}><td><CallResult value={call.result}/></td><td>Lead</td><td>{formatDate(call.callAt)}</td><td className="notes-cell">{call.notes||"—"}</td><td>{call.assignedEmployee||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-history">لا توجد مكالمات مسجلة لهذا العميل.</div>}</div><div className="dialog-foot"><button className="secondary" onClick={onClose}>إغلاق</button></div></section></div>;
}

function Metric({ label, value, hint, tone }: { label: string; value: number; hint: string; tone: string }) { return <article className="metric"><span className={`metric-icon ${tone}`}>◆</span><div><small>{label}</small><strong>{String(value).padStart(2,"0")}</strong><p>{hint}</p></div></article>; }
function Status({ status }: { status: Employee["status"] }) { const map = { active:"نشط", invited:"دعوة معلقة", disabled:"موقوف" }; return <span className={`status ${status}`}><i />{map[status]}</span>; }
function initials(name: string) { return name.split(" ").slice(0,2).map((part) => part[0]).join(""); }
function parseOptions(field: Field) { try { return JSON.parse(field.optionsJson || "[]") as string[]; } catch { return []; } }

function EmployeeDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState<Record<string, unknown>>({ startDate: new Date().toISOString().slice(0,10) }); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.fields.filter((f)=>f.visible);
  async function submit(e: FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","email","phone","departmentId","jobTitleId","roleId","branchId","status"]);const customData=Object.fromEntries(Object.entries(values).filter(([k])=>!standard.has(k)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر الحفظ");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog employee-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">＋</span><div><h2>إضافة موظف جديد</h2><p>بيانات الملف الوظيفي وحساب الدخول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>▤</span><p>هذا النموذج ديناميكي. يمكنك إخفاء أي حقل أو إضافة حقول جديدة من «مصمم النماذج».</p></div><div className="dynamic-grid dialog-fields">{fields.map((f)=><DynamicField key={f.id} field={f} value={values[f.fieldKey]} setValue={(v)=>setValues((current)=>({...current,[f.fieldKey]:v}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"إنشاء ملف الموظف"}</button></div></form></div>;
}

function DynamicField({ field, value, setValue, data, values, disabled=false }: { field: Field; value: unknown; setValue:(v:unknown)=>void; data:Setup; values:Record<string,unknown>; disabled?:boolean }) {
  let options:{id:string|number;name:string}[]=parseOptions(field).map((name)=>({id:name,name}));
  if(field.fieldKey==="departmentId") options=data.departments.map((d)=>({id:d.id,name:d.name}));
  if(field.fieldKey==="jobTitleId") options=data.jobTitles.filter((j)=>!values.departmentId||j.departmentId===Number(values.departmentId)).map((j)=>({id:j.id,name:j.name}));
  if(field.fieldKey==="roleId") options=data.roles.map((r)=>({id:r.id,name:r.name}));
  if(field.fieldKey==="assignedEmployeeId") options=data.employees.filter((employee)=>employee.status==="active").map((employee)=>({id:employee.id,name:employee.fullName}));
  if(field.fieldKey==="branchId") options=data.branches.filter((branch)=>branch.isActive||Number(value)===branch.id).map((branch)=>({id:branch.id,name:branch.name}));
  const common={disabled,required:!!field.required};
  if(field.type==="textarea") return <label className="full"><span>{field.label}{field.required?" *":""}</span><textarea value={String(value??"")} placeholder={field.placeholder} onChange={(e)=>setValue(e.target.value)} disabled={disabled} required={!!field.required}/></label>;
  if(field.type==="checkbox") { const selected=Array.isArray(value)?value as string[]:[]; return <fieldset className="full document-field"><legend>{field.label}</legend><div>{options.map((o)=><label key={o.id}><input type="checkbox" checked={selected.includes(String(o.id))} disabled={disabled} onChange={(e)=>setValue(e.target.checked?[...selected,String(o.id)]:selected.filter((x)=>x!==String(o.id)))} /><span>✓</span>{o.name}</label>)}</div></fieldset>; }
  return <label className={field.width==="full"?"full":""}><span>{field.label}{field.required?" *":""}</span>{field.type==="select"?<select value={String(value??"")} onChange={(e)=>setValue(e.target.value)} {...common}><option value="">{field.placeholder}</option>{options.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input value={String(value??"")} onChange={(e)=>setValue(e.target.value)} placeholder={field.placeholder} type={field.type} {...common}/>}</label>;
}
function BaseDialog({ title, subtitle, icon, onClose, onSubmit, children, busyText="جارٍ الحفظ...", submitText="حفظ" }: { title:string;subtitle:string;icon:string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode;busyText?:string;submitText?:string }) { const [busy,setBusy]=useState(false); return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={(e)=>{setBusy(true);onSubmit(e)}}><div className="dialog-head"><div><span className="dialog-icon">{icon}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div><button type="button" onClick={onClose}>×</button></div><div className="dynamic-grid dialog-fields">{children}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?busyText:submitText}</button></div></form></div>; }

function DepartmentDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة قسم" subtitle="سيظهر مباشرة داخل نموذج الموظف" icon="≡" onClose={onClose} submitText="إضافة القسم" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),parentId:f.get("parentId"),color:f.get("color"),supportEnabled:f.get("supportEnabled")==="on"})}}><label className="full"><span>اسم القسم *</span><input name="name" required placeholder="مثال: التسويق" /></label><label><span>القسم الرئيسي</span><select name="parentId"><option value="">بدون قسم رئيسي</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span>لون القسم</span><input name="color" type="color" defaultValue="#2f6b5f" /></label><label className="inline-check full"><input type="checkbox" name="supportEnabled" /> تفعيل خيارات الدعم لهذا القسم</label></BaseDialog>; }
function BranchDialog({data,branch,onClose,onSubmit}:{data:Setup;branch:Branch|null;onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { const [values,setValues]=useState<Record<string,unknown>>(branch?{name:branch.name,address:branch.address,primaryPhone:branch.primaryPhone,secondaryPhone:branch.secondaryPhone,email:branch.email,socialUrl:branch.socialUrl,isActive:branch.isActive?"نشط":"غير نشط"}:{isActive:"نشط"}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ الفرع");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog employee-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">⌂</span><div><h2>{branch?"تعديل بيانات الفرع":"إضافة فرع جديد"}</h2><p>مصدر موحد للفروع في كل نماذج النظام.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>النموذج ديناميكي، وتحديث الفرع ينعكس فورًا على الموظفين والـLeads والمكالمات المرتبطة.</p></div><div className="dynamic-grid dialog-fields">{data.branchFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":branch?"حفظ التعديلات":"إضافة الفرع"}</button></div></form></div>; }
function JobDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة دور وظيفي" subtitle="اختر القسم الذي تتبعه الوظيفة" icon="◆" onClose={onClose} submitText="إضافة الوظيفة" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),departmentId:f.get("departmentId")})}}><label className="full"><span>اسم الوظيفة *</span><input name="name" required placeholder="مثال: مسؤول مبيعات" /></label><label className="full"><span>القسم *</span><select name="departmentId" required><option value="">اختر القسم</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></BaseDialog>; }
function FieldDialog({onClose,onSubmit}:{onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="حقل جديد" subtitle="سيظهر داخل نموذج الإدخال المحدد" icon="▤" onClose={onClose} submitText="إضافة الحقل" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({formKey:f.get("formKey"),label:f.get("label"),type:f.get("type"),placeholder:f.get("placeholder"),width:f.get("width"),required:f.get("required")==="on"})}}><label className="full"><span>النموذج *</span><select name="formKey" required><option value="employee">الموظف</option><option value="branch">الفرع</option><option value="lead">Lead جديدة</option><option value="call">المكالمة</option><option value="lead_details">استكمال بيانات العميل</option><option value="followup">المتابعة</option></select></label><label className="full"><span>اسم الحقل *</span><input name="label" required /></label><label><span>النوع</span><select name="type"><option value="text">نص</option><option value="number">رقم</option><option value="date">تاريخ</option><option value="textarea">نص طويل</option></select></label><label><span>العرض</span><select name="width"><option value="half">نصف صف</option><option value="full">صف كامل</option></select></label><label className="full"><span>النص الإرشادي</span><input name="placeholder" /></label><label className="inline-check full"><input type="checkbox" name="required" /> حقل إلزامي</label></BaseDialog>; }
