"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Department = { id: number; name: string; color: string; parentId: number | null; parentName: string | null; supportEnabled: number; isActive: number; jobCount: number };
type JobTitle = { id: number; name: string; departmentId: number; department: string };
type Role = { id: number; name: string; description: string };
type Employee = { id: number; fullName: string; email: string; phone: string; status: "active" | "invited" | "disabled"; departmentId: number; jobTitleId: number; roleId: number; department: string; jobTitle: string; role: string };
type Field = { id: number; fieldKey: string; label: string; type: string; placeholder: string; required: number; visible: number; sortOrder: number; width: "full" | "half"; version: number; optionsJson: string };
type Lead = { id: number; fullName: string; primaryPhone: string; secondaryPhone: string; email: string; source: string; campaign: string; interest: string; status: string; priority: string; notes: string; assignedEmployeeId: number; assignedEmployee: string; callCount: number; createdAt: string };
type CallRecord = { id: number; leadId: number | null; phone: string; direction: string; result: string; assignedEmployeeId: number; assignedEmployee: string; leadName: string | null; callAt: string; notes: string };
type Setup = { departments: Department[]; jobTitles: JobTitle[]; roles: Role[]; employees: Employee[]; fields: Field[]; leads: Lead[]; calls: CallRecord[]; leadFields: Field[]; callFields: Field[] };
type Tab = "overview" | "departments" | "jobs" | "employees" | "leaves" | "permissions" | "forms" | "leads" | "calls";
type Dialog = "employee" | "department" | "job" | "field" | "lead" | "call" | null;

const emptySetup: Setup = { departments: [], jobTitles: [], roles: [], employees: [], fields: [], leads: [], calls: [], leadFields: [], callFields: [] };
const titles: Record<Tab, [string, string]> = {
  overview: ["إدارة الموارد البشرية", "هيكل الشركة والموظفون في مكان واحد"], departments: ["أقسام الشركة", "الأقسام الرئيسية والفرعية التي تظهر في نموذج الموظف"], jobs: ["الأدوار الوظيفية", "كل قسم وتحته الوظائف المتاحة داخله"], employees: ["الموظفون", "بيانات الموظفين وحساباتهم على النظام"], leaves: ["الإجازات", "أنواع الإجازات وسياسات الاستحقاق"], permissions: ["الصلاحيات", "صلاحيات الصفحات والإجراءات لكل مجموعة"], forms: ["مصمم النماذج", "تحكم كامل في حقول إدخال بيانات الموظف"],
  leads: ["العملاء المحتملون", "تسجيل وتوزيع الـLeads ومتابعة حالتها الأولية"], calls: ["سجل المكالمات", "تسجيل مكالمة جديدة وربطها تلقائيًا بالعميل"],
};

export function CrmShell() {
  const [tab, setTab] = useState<Tab>("overview"); const [data, setData] = useState<Setup>(emptySetup); const [loading, setLoading] = useState(true); const [dialog, setDialog] = useState<Dialog>(null); const [notice, setNotice] = useState("");
  async function load() { const [setupResponse, salesResponse] = await Promise.all([fetch("/api/setup", { cache: "no-store" }), fetch("/api/leads", { cache: "no-store" })]); const setup = await setupResponse.json(); const sales = await salesResponse.json(); if (!setupResponse.ok) throw new Error(setup.error || "تعذر تحميل البيانات"); if (!salesResponse.ok) throw new Error(sales.error || "تعذر تحميل العملاء"); setData({ ...setup, ...sales }); }
  useEffect(() => { load().catch((error) => setNotice(error.message)).finally(() => setLoading(false)); }, []);
  async function mutate(payload: Record<string, unknown>) { const response = await fetch("/api/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); }
  async function mutateSales(payload: Record<string, unknown>) { const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); return result; }
  const [title, subtitle] = titles[tab];
  return <main className="app-shell" dir="rtl">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">م</span><div><strong>مسار</strong><small>إدارة علاقات العملاء</small></div></div>
      <nav aria-label="التنقل الرئيسي">
        <button className={`nav-group ${tab === "overview" ? "active" : ""}`} onClick={() => setTab("overview")}><span className="nav-icon">≡</span><span><strong>إدارة الموارد البشرية</strong><small>Employees Manager</small></span><b>⌄</b></button>
        <div className="subnav">
          <SubNav label="أقسام الشركة" active={tab === "departments"} onClick={() => setTab("departments")} />
          <SubNav label="الأدوار الوظيفية" active={tab === "jobs"} onClick={() => setTab("jobs")} />
          <SubNav label="الإجازات" active={tab === "leaves"} onClick={() => setTab("leaves")} />
          <SubNav label="الموظفون" active={tab === "employees"} onClick={() => setTab("employees")} />
        </div>
        <div className="nav-separator" />
        <NavItem active={tab === "permissions"} icon="⌾" label="الصلاحيات" onClick={() => setTab("permissions")} />
        <NavItem active={tab === "forms"} icon="▤" label="مصمم النماذج" onClick={() => setTab("forms")} />
        <div className="nav-separator" />
        <button className={`nav-group sales ${tab === "leads" || tab === "calls" ? "active" : ""}`} onClick={() => setTab("leads")}><span className="nav-icon">◇</span><span><strong>العملاء والمبيعات</strong><small>Leads & Calls</small></span><b>⌄</b></button>
        <div className="subnav"><SubNav label="العملاء المحتملون" active={tab === "leads"} onClick={() => setTab("leads")} /><SubNav label="سجل المكالمات" active={tab === "calls"} onClick={() => setTab("calls")} /></div>
        <NavItem disabled icon="◷" label="المتابعات" badge="المرحلة 3" /><NavItem disabled icon="◫" label="المدفوعات" badge="المرحلة 4" /><NavItem disabled icon="◎" label="الجروبات" badge="المرحلة 5" />
      </nav>
      <div className="phase-card"><span>المرحلة الحالية</span><strong>02 — العملاء والمكالمات</strong><div className="progress phase-two"><i /></div><small>تسجيل العميل، منع التكرار وتوزيع المسؤولية</small></div>
      <div className="profile"><span className="avatar">أم</span><div><strong>أحمد منصور</strong><small>مدير النظام</small></div><button>•••</button></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">مسار CRM <b>/</b> {tab === "leads" || tab === "calls" ? "العملاء والمبيعات" : "الموارد البشرية"}</span><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div><div className="top-actions"><button className="icon-button">♢<i /></button>{tab === "departments" && <button className="primary" onClick={() => setDialog("department")}>＋ إضافة قسم</button>}{tab === "jobs" && <button className="primary" onClick={() => setDialog("job")}>＋ إضافة وظيفة</button>}{tab === "employees" && <button className="primary" onClick={() => setDialog("employee")}>＋ إضافة موظف</button>}{tab === "forms" && <button className="primary" onClick={() => setDialog("field")}>＋ إضافة حقل</button>}{tab === "leads" && <button className="primary" onClick={() => setDialog("lead")}>＋ تسجيل Lead</button>}{tab === "calls" && <button className="primary" onClick={() => setDialog("call")}>＋ تسجيل مكالمة</button>}</div></header>
      {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {loading ? <Loading /> : <Page tab={tab} data={data} mutate={mutate} open={setDialog} setNotice={setNotice} />}
    </section>
    {dialog === "employee" && <EmployeeDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createEmployee", ...payload }); setDialog(null); setNotice("تم إنشاء حساب الموظف وإضافة ملفه بنجاح"); }} />}
    {dialog === "department" && <DepartmentDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createDepartment", ...payload }); setDialog(null); setNotice("تمت إضافة القسم وسيظهر الآن في نموذج الموظف"); }} />}
    {dialog === "job" && <JobDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createJobTitle", ...payload }); setDialog(null); setNotice("تمت إضافة الوظيفة تحت القسم المحدد"); }} />}
    {dialog === "field" && <FieldDialog onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "addField", ...payload }); setDialog(null); setNotice("تمت إضافة الحقل إلى نموذج الموظف"); }} />}
    {dialog === "lead" && <LeadDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "createLead", ...payload }); setDialog(null); setNotice("تم تسجيل العميل المحتمل وتعيين الموظف المسؤول"); }} />}
    {dialog === "call" && <CallDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { const result = await mutateSales({ action: "createCall", ...payload }); setDialog(null); setNotice(result.matchedLead ? "تم تسجيل المكالمة وربطها بالعميل الموجود" : "تم تسجيل المكالمة كرقم غير مرتبط بعميل"); }} />}
  </main>;
}

function Page({ tab, data, mutate, open, setNotice }: { tab: Tab; data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; open: (d: Dialog) => void; setNotice: (s: string) => void }) {
  if (tab === "overview") return <HrOverview data={data} go={open} />;
  if (tab === "departments") return <Departments data={data} add={() => open("department")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "jobs") return <Jobs data={data} add={() => open("job")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "employees") return <Employees data={data} add={() => open("employee")} />;
  if (tab === "leaves") return <Leaves />;
  if (tab === "permissions") return <Permissions roles={data.roles} />;
  if (tab === "leads") return <LeadsPage data={data} addLead={() => open("lead")} addCall={() => open("call")} />;
  if (tab === "calls") return <CallsPage data={data} add={() => open("call")} />;
  return <FormBuilder fields={data.fields} data={data} mutate={mutate} onAdd={() => open("field")} />;
}

function SubNav({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button className={active ? "active" : ""} onClick={onClick}><i />{label}</button>; }
function NavItem({ active, disabled, icon, label, badge, onClick }: { active?: boolean; disabled?: boolean; icon: string; label: string; badge?: string; onClick?: () => void }) { return <button className={`nav-item ${active ? "active" : ""} ${disabled ? "disabled" : ""}`} onClick={onClick} disabled={disabled}><span className="nav-icon">{icon}</span><span>{label}</span>{badge && <em>{badge}</em>}</button>; }
function Loading() { return <div className="loading-grid"><div /><div /><div /><article /></div>; }

function HrOverview({ data }: { data: Setup; go: (d: Dialog) => void }) {
  return <div className="content-stack"><section className="metrics"><Metric label="الموظفون" value={data.employees.length} hint="ملفات مسجلة" tone="green" /><Metric label="أقسام الشركة" value={data.departments.length} hint="رئيسية وفرعية" tone="blue" /><Metric label="الأدوار الوظيفية" value={data.jobTitles.length} hint="مرتبطة بالأقسام" tone="orange" /><Metric label="حسابات نشطة" value={data.employees.filter((e) => e.status === "active").length} hint="تعمل على النظام" tone="purple" /></section><section className="hr-map"><div className="hr-intro"><span>نظام موارد بشرية مترابط</span><h2>ابدأ بالهيكل، ثم أضف فريقك</h2><p>القسم يحدد الوظائف المتاحة، والوظيفة ومجموعة الصلاحيات تحددان ما يمكن للموظف رؤيته وتنفيذه داخل النظام.</p></div><div className="flow-cards"><FlowCard n="01" title="أقسام الشركة" text="أضف الأقسام الرئيسية والفرعية" /><b>←</b><FlowCard n="02" title="الأدوار الوظيفية" text="عرّف الوظائف داخل كل قسم" /><b>←</b><FlowCard n="03" title="الموظفون" text="أنشئ الملف والحساب والصلاحيات" /></div><div className="quick-row"><button onClick={() => go("department")}>＋ قسم جديد</button><button onClick={() => go("job")}>＋ وظيفة جديدة</button><button onClick={() => go("employee")}>＋ موظف جديد</button></div></section></div>;
}
function FlowCard({ n, title, text }: { n: string; title: string; text: string }) { return <article><span>{n}</span><strong>{title}</strong><small>{text}</small></article>; }

function Departments({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteDepartment", id }); setNotice("تم حذف القسم"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <section className="panel"><div className="panel-head"><div><h2>قائمة أقسام الشركة</h2><p>الأقسام هنا هي المصدر المباشر لقائمة القسم داخل نموذج الموظف.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث عن قسم..." /></label><button className="secondary" onClick={add}>＋ إضافة جديد</button></div></div><div className="table-wrap"><table className="departments-table"><thead><tr><th>#</th><th>اسم القسم</th><th>القسم الرئيسي</th><th>الدعم</th><th>عدد الوظائف</th><th>الإجراءات</th></tr></thead><tbody>{data.departments.map((d, i) => <tr key={d.id}><td>{i + 1}</td><td><strong className="dept-title"><i style={{ background: d.color }} />{d.name}</strong></td><td>{d.parentName ? <span>{d.parentName}</span> : <span className="tag no-parent">بدون قسم رئيسي</span>}</td><td>{d.supportEnabled ? <span className="tag support">مفعّل</span> : <span className="tag off">غير مفعّل</span>}</td><td><span className="count-chip">{d.jobCount} وظائف</span></td><td><div className="actions"><button className="edit">تعديل</button><button className="delete" onClick={() => remove(d.id)}>حذف</button></div></td></tr>)}</tbody></table></div></section>;
}

function Jobs({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteJobTitle", id }); setNotice("تم حذف الوظيفة"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <div className="jobs-layout"><div className="jobs-toolbar"><p>كل وظيفة مرتبطة بقسم واحد، وتظهر للموظف بعد اختيار القسم.</p><button className="secondary" onClick={add}>＋ إضافة وظيفة</button></div><div className="department-groups">{data.departments.map((department) => { const jobs = data.jobTitles.filter((job) => job.departmentId === department.id); return <section className="job-group" key={department.id}><header><span style={{ background: department.color }}>{initials(department.name)}</span><div><h2>{department.name}</h2><p>{jobs.length} أدوار وظيفية</p></div><button onClick={add}>＋</button></header><div>{jobs.length ? jobs.map((job) => <article key={job.id}><div><strong>{job.name}</strong><small>يتبع قسم {department.name}</small></div><button className="row-menu">تعديل</button><button className="row-menu danger" onClick={() => remove(job.id)}>حذف</button></article>) : <p className="empty-line">لا توجد وظائف داخل هذا القسم بعد.</p>}</div></section>; })}</div></div>;
}

function Employees({ data, add }: { data: Setup; add: () => void }) {
  const active = data.employees.filter((e) => e.status === "active").length;
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي الموظفين" value={data.employees.length} hint="كل الملفات" tone="green" /><Metric label="الحسابات النشطة" value={active} hint="جاهزة للعمل" tone="blue" /><Metric label="دعوات معلقة" value={data.employees.filter((e) => e.status === "invited").length} hint="في انتظار التفعيل" tone="orange" /><Metric label="الأقسام" value={data.departments.length} hint="هيكل الشركة" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>دليل الموظفين</h2><p>ملف الموظف، القسم، الدور الوظيفي، وصلاحيات النظام.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو البريد..." /></label><button className="secondary" onClick={add}>＋ موظف جديد</button></div></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>القسم</th><th>الدور الوظيفي</th><th>الصلاحيات</th><th>الحالة</th><th /></tr></thead><tbody>{data.employees.map((e) => <tr key={e.id}><td><div className="employee"><span>{initials(e.fullName)}</span><div><strong>{e.fullName}</strong><small>{e.email}</small></div></div></td><td><span className="department-dot" style={{ background: data.departments.find((d) => d.id === e.departmentId)?.color }} />{e.department}</td><td>{e.jobTitle}</td><td><span className="role-chip">{e.role}</span></td><td><Status status={e.status} /></td><td><button className="row-menu">•••</button></td></tr>)}</tbody></table></div><div className="table-footer"><span>عرض {data.employees.length} موظفين</span><button className="primary" onClick={add}>＋ إضافة موظف</button></div></section></div>;
}

function Leaves() { return <section className="panel leaves-panel"><div className="panel-head"><div><h2>أنواع الإجازات</h2><p>الجزء ظاهر داخل الموارد البشرية، وسيتم تفعيل سياساته عند اعتماد متطلبات الإجازات.</p></div><span className="tag support">مخطط</span></div><div className="leave-grid"><article><span>سنوية</span><strong>21 يوم</strong><small>الرصيد الافتراضي</small></article><article><span>عارضة</span><strong>6 أيام</strong><small>ضمن الرصيد السنوي</small></article><article><span>مرضية</span><strong>حسب اللائحة</strong><small>تحتاج مستندًا</small></article></div><div className="guard-note"><span>◈</span><div><strong>لم يتم تفعيل عمليات الإجازات بعد</strong><p>سنحدد دورة الطلب والموافقة والأرصدة في خطوة مستقلة حتى لا نفترض سياسة غير معتمدة.</p></div></div></section>; }

function Permissions({ roles }: { roles: Role[] }) { const rows = ["الموظفون", "الأقسام والوظائف", "إعدادات النماذج", "العملاء المحتملون"]; return <div className="split-layout"><section className="panel roles-list"><div className="panel-head"><div><h2>مجموعات الصلاحيات</h2><p>صلاحيات استخدام النظام، وليست الدور الوظيفي.</p></div><button className="secondary">＋ مجموعة جديدة</button></div>{roles.map((role, i) => <button key={role.id} className={`role-row ${i === 0 ? "selected" : ""}`}><span className="role-symbol">{i === 0 ? "♛" : "◆"}</span><div><strong>{role.name}</strong><small>{role.description}</small></div></button>)}</section><section className="panel permission-matrix"><div className="panel-head"><div><span className="mini-label">صلاحيات المجموعة</span><h2>مدير النظام</h2></div><button className="primary">حفظ التغييرات</button></div><table><thead><tr><th>الصفحة</th><th>عرض</th><th>إضافة</th><th>تعديل</th><th>حذف</th></tr></thead><tbody>{rows.map((row, ri) => <tr key={row}><td><strong>{row}</strong></td>{[0,1,2,3].map((c) => <td key={c}><label className="check"><input type="checkbox" defaultChecked={ri < 3 || c < 2} /><span>✓</span></label></td>)}</tr>)}</tbody></table></section></div>; }

function FormBuilder({ fields, data, mutate, onAdd }: { fields: Field[]; data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; onAdd: () => void }) {
  const [saving, setSaving] = useState<number | null>(null); const previewFields = fields.filter((f) => f.visible).slice(0, 8);
  return <div className="builder-layout"><section className="panel field-panel"><div className="panel-head"><div><span className="version">نسخة {fields[0]?.version ?? 1}</span><h2>نموذج بيانات الموظف</h2><p>{fields.length} حقلًا قابلًا للتحكم من هنا.</p></div><button className="secondary" onClick={onAdd}>＋ حقل جديد</button></div><div className="field-list">{fields.map((f, i) => <div className={`field-row ${!f.visible ? "muted" : ""}`} key={f.id}><span className="drag">⠿</span><span className="field-index">{String(i + 1).padStart(2,"0")}</span><div className="field-info"><strong>{f.label}</strong><small>{f.fieldKey} · {f.type}</small></div><label className="mini-toggle"><input type="checkbox" checked={!!f.required} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:!!f.visible, required:e.target.checked }); setSaving(null); }} /><span />إلزامي</label><label className="mini-toggle"><input type="checkbox" checked={!!f.visible} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:e.target.checked, required:!!f.required }); setSaving(null); }} /><span />ظاهر</label><button className="row-menu">{saving === f.id ? "…" : "•••"}</button></div>)}</div></section><section className="panel preview-panel"><div className="preview-head"><div><span className="live-dot" />معاينة مباشرة</div><span>أول الحقول</span></div><div className="form-preview"><div className="preview-title"><span>＋</span><div><h3>موظف جديد</h3><p>المعاينة تتغير مع إعدادات الحقول.</p></div></div><div className="dynamic-grid">{previewFields.map((f) => <DynamicField key={f.id} field={f} value="" setValue={() => {}} data={data} values={{}} disabled />)}</div></div></section></div>;
}

function LeadsPage({ data, addLead, addCall }: { data: Setup; addLead: () => void; addCall: () => void }) {
  const newCount = data.leads.filter((lead) => lead.status === "new").length;
  const urgent = data.leads.filter((lead) => lead.priority === "urgent").length;
  return <div className="content-stack lead-board">
    <section className="metrics"><Metric label="إجمالي الـLeads" value={data.leads.length} hint="عملاء محتملون" tone="green" /><Metric label="جديدة" value={newCount} hint="لم تبدأ المتابعة" tone="blue" /><Metric label="أولوية عاجلة" value={urgent} hint="تحتاج تصرفًا سريعًا" tone="orange" /><Metric label="المكالمات" value={data.calls.length} hint="مسجلة في المرحلة" tone="purple" /></section>
    <section className="panel"><div className="panel-head"><div><h2>قائمة العملاء المحتملين</h2><p>رقم الهاتف فريد، وأي محاولة لتسجيله مرة أخرى ستظهر العميل الموجود.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو الهاتف..." /></label><button className="secondary" onClick={addCall}>☎ مكالمة جديدة</button><button className="primary" onClick={addLead}>＋ Lead جديدة</button></div></div>
      {data.leads.length ? <div className="table-wrap"><table><thead><tr><th>العميل</th><th>المصدر</th><th>الخدمة المطلوبة</th><th>الموظف المسؤول</th><th>الأولوية</th><th>الحالة</th><th>المكالمات</th><th /></tr></thead><tbody>{data.leads.map((lead) => <tr key={lead.id}><td><div className="employee lead-person"><span>{initials(lead.fullName)}</span><div><strong>{lead.fullName}</strong><small>{lead.primaryPhone}</small></div></div></td><td><span className="source-chip">{lead.source}</span></td><td>{lead.interest || "—"}</td><td>{lead.assignedEmployee || "غير معيّن"}</td><td><Priority value={lead.priority} /></td><td><LeadStatus value={lead.status} /></td><td><button className="calls-count" onClick={addCall}>☎ {lead.callCount}</button></td><td><button className="row-menu">•••</button></td></tr>)}</tbody></table></div> : <div className="empty"><span>◇</span><h3>لا توجد Leads حتى الآن</h3><p>سجل أول عميل محتمل وحدد مصدره والموظف المسؤول.</p><button className="primary" onClick={addLead}>＋ تسجيل Lead جديدة</button></div>}
      <div className="table-footer"><span>إجمالي {data.leads.length} عميل محتمل</span><span className="duplicate-guard">✓ منع تكرار الهاتف مفعّل</span></div>
    </section>
  </div>;
}

function CallsPage({ data, add }: { data: Setup; add: () => void }) {
  const answered = data.calls.filter((call) => call.result === "answered").length;
  const linked = data.calls.filter((call) => call.leadId).length;
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي المكالمات" value={data.calls.length} hint="كل المكالمات المسجلة" tone="green" /><Metric label="تم الرد" value={answered} hint="مكالمات مكتملة" tone="blue" /><Metric label="مرتبطة بعميل" value={linked} hint="تم التعرف على الرقم" tone="orange" /><Metric label="أرقام جديدة" value={data.calls.length - linked} hint="غير مرتبطة بـLead" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>سجل المكالمات</h2><p>يتم البحث عن رقم الهاتف وربطه تلقائيًا بعميل موجود.</p></div><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>{data.calls.length ? <div className="table-wrap"><table><thead><tr><th>العميل / الرقم</th><th>نوع المكالمة</th><th>النتيجة</th><th>الموظف المسؤول</th><th>التوقيت</th><th>الملاحظات</th></tr></thead><tbody>{data.calls.map((call) => <tr key={call.id}><td><div className="call-identity"><strong>{call.leadName || "رقم غير مسجل"}</strong><small>{call.phone}</small></div></td><td><span className={`direction ${call.direction}`}>{call.direction === "incoming" ? "↙ واردة" : "↗ صادرة"}</span></td><td><CallResult value={call.result} /></td><td>{call.assignedEmployee || "غير معيّن"}</td><td>{formatDate(call.callAt)}</td><td className="notes-cell">{call.notes || "—"}</td></tr>)}</tbody></table></div> : <div className="empty"><span>☎</span><h3>لا توجد مكالمات مسجلة</h3><p>سجل مكالمة واردة أو صادرة، وسيتم ربطها بالـLead تلقائيًا.</p><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>}</section></div>;
}

function Priority({ value }: { value: string }) { const labels: Record<string,string> = { normal:"عادية", high:"مرتفعة", urgent:"عاجلة" }; return <span className={`priority ${value}`}>{labels[value] || value}</span>; }
function LeadStatus({ value }: { value: string }) { const labels: Record<string,string> = { new:"جديدة", contacted:"تم التواصل", qualified:"مؤهلة", unqualified:"غير مؤهلة" }; return <span className={`lead-status ${value}`}><i />{labels[value] || value}</span>; }
function CallResult({ value }: { value: string }) { const labels: Record<string,string> = { answered:"تم الرد", no_answer:"لم يرد", busy:"مشغول", wrong_number:"رقم خاطئ", callback:"معاودة الاتصال" }; return <span className={`call-result ${value}`}>{labels[value] || value}</span>; }
function formatDate(value: string) { try { return new Intl.DateTimeFormat("ar-EG", { dateStyle:"short", timeStyle:"short" }).format(new Date(value)); } catch { return value; } }

function LeadDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const [values,setValues]=useState<Record<string,unknown>>({priority:"عادية"}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.leadFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","primaryPhone","secondaryPhone","email","source","campaign","interest","priority","assignedEmployeeId","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل العميل");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◇</span><div><h2>تسجيل Lead جديدة</h2><p>بيانات العميل ومصدره والموظف المسؤول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error duplicate-error">{error}</p>}<div className="employee-form-note"><span>✓</span><p>سيتم تنظيف رقم الهاتف ومراجعته لمنع تسجيل نفس العميل مرتين.</p></div><div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التحقق والحفظ...":"تسجيل العميل"}</button></div></form></div>;
}

function CallDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const now=new Date(); now.setMinutes(now.getMinutes()-now.getTimezoneOffset()); const [values,setValues]=useState<Record<string,unknown>>({direction:"صادرة",result:"تم الرد",callAt:now.toISOString().slice(0,16)}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.callFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["phone","direction","result","assignedEmployeeId","callAt","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل المكالمة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog compact-sales" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">☎</span><div><h2>تسجيل مكالمة جديدة</h2><p>لو الرقم مسجل سيتم ربط المكالمة بالعميل تلقائيًا.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التسجيل...":"حفظ المكالمة"}</button></div></form></div>;
}

function Metric({ label, value, hint, tone }: { label: string; value: number; hint: string; tone: string }) { return <article className="metric"><span className={`metric-icon ${tone}`}>◆</span><div><small>{label}</small><strong>{String(value).padStart(2,"0")}</strong><p>{hint}</p></div></article>; }
function Status({ status }: { status: Employee["status"] }) { const map = { active:"نشط", invited:"دعوة معلقة", disabled:"موقوف" }; return <span className={`status ${status}`}><i />{map[status]}</span>; }
function initials(name: string) { return name.split(" ").slice(0,2).map((part) => part[0]).join(""); }
function parseOptions(field: Field) { try { return JSON.parse(field.optionsJson || "[]") as string[]; } catch { return []; } }

function EmployeeDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState<Record<string, unknown>>({ startDate: new Date().toISOString().slice(0,10) }); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.fields.filter((f)=>f.visible);
  async function submit(e: FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","email","phone","departmentId","jobTitleId","roleId","status"]);const customData=Object.fromEntries(Object.entries(values).filter(([k])=>!standard.has(k)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر الحفظ");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog employee-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">＋</span><div><h2>إضافة موظف جديد</h2><p>بيانات الملف الوظيفي وحساب الدخول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>▤</span><p>هذا النموذج ديناميكي. يمكنك إخفاء أي حقل أو إضافة حقول جديدة من «مصمم النماذج».</p></div><div className="dynamic-grid dialog-fields">{fields.map((f)=><DynamicField key={f.id} field={f} value={values[f.fieldKey]} setValue={(v)=>setValues((current)=>({...current,[f.fieldKey]:v}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"إنشاء ملف الموظف"}</button></div></form></div>;
}

function DynamicField({ field, value, setValue, data, values, disabled=false }: { field: Field; value: unknown; setValue:(v:unknown)=>void; data:Setup; values:Record<string,unknown>; disabled?:boolean }) {
  let options:{id:string|number;name:string}[]=parseOptions(field).map((name)=>({id:name,name}));
  if(field.fieldKey==="departmentId") options=data.departments.map((d)=>({id:d.id,name:d.name}));
  if(field.fieldKey==="jobTitleId") options=data.jobTitles.filter((j)=>!values.departmentId||j.departmentId===Number(values.departmentId)).map((j)=>({id:j.id,name:j.name}));
  if(field.fieldKey==="roleId") options=data.roles.map((r)=>({id:r.id,name:r.name}));
  if(field.fieldKey==="assignedEmployeeId") options=data.employees.filter((employee)=>employee.status==="active").map((employee)=>({id:employee.id,name:employee.fullName}));
  const common={disabled,required:!!field.required};
  if(field.type==="textarea") return <label className="full"><span>{field.label}{field.required?" *":""}</span><textarea value={String(value??"")} placeholder={field.placeholder} onChange={(e)=>setValue(e.target.value)} disabled={disabled} required={!!field.required}/></label>;
  if(field.type==="checkbox") { const selected=Array.isArray(value)?value as string[]:[]; return <fieldset className="full document-field"><legend>{field.label}</legend><div>{options.map((o)=><label key={o.id}><input type="checkbox" checked={selected.includes(String(o.id))} disabled={disabled} onChange={(e)=>setValue(e.target.checked?[...selected,String(o.id)]:selected.filter((x)=>x!==String(o.id)))} /><span>✓</span>{o.name}</label>)}</div></fieldset>; }
  return <label className={field.width==="full"?"full":""}><span>{field.label}{field.required?" *":""}</span>{field.type==="select"?<select value={String(value??"")} onChange={(e)=>setValue(e.target.value)} {...common}><option value="">{field.placeholder}</option>{options.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input value={String(value??"")} onChange={(e)=>setValue(e.target.value)} placeholder={field.placeholder} type={field.type} {...common}/>}</label>;
}
function BaseDialog({ title, subtitle, icon, onClose, onSubmit, children, busyText="جارٍ الحفظ...", submitText="حفظ" }: { title:string;subtitle:string;icon:string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode;busyText?:string;submitText?:string }) { const [busy,setBusy]=useState(false); return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={(e)=>{setBusy(true);onSubmit(e)}}><div className="dialog-head"><div><span className="dialog-icon">{icon}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div><button type="button" onClick={onClose}>×</button></div><div className="dynamic-grid dialog-fields">{children}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?busyText:submitText}</button></div></form></div>; }

function DepartmentDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة قسم" subtitle="سيظهر مباشرة داخل نموذج الموظف" icon="≡" onClose={onClose} submitText="إضافة القسم" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),parentId:f.get("parentId"),color:f.get("color"),supportEnabled:f.get("supportEnabled")==="on"})}}><label className="full"><span>اسم القسم *</span><input name="name" required placeholder="مثال: التسويق" /></label><label><span>القسم الرئيسي</span><select name="parentId"><option value="">بدون قسم رئيسي</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span>لون القسم</span><input name="color" type="color" defaultValue="#2f6b5f" /></label><label className="inline-check full"><input type="checkbox" name="supportEnabled" /> تفعيل خيارات الدعم لهذا القسم</label></BaseDialog>; }
function JobDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة دور وظيفي" subtitle="اختر القسم الذي تتبعه الوظيفة" icon="◆" onClose={onClose} submitText="إضافة الوظيفة" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),departmentId:f.get("departmentId")})}}><label className="full"><span>اسم الوظيفة *</span><input name="name" required placeholder="مثال: مسؤول مبيعات" /></label><label className="full"><span>القسم *</span><select name="departmentId" required><option value="">اختر القسم</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></BaseDialog>; }
function FieldDialog({onClose,onSubmit}:{onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="حقل جديد" subtitle="سيظهر داخل نموذج الموظف" icon="▤" onClose={onClose} submitText="إضافة الحقل" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({label:f.get("label"),type:f.get("type"),placeholder:f.get("placeholder"),width:f.get("width"),required:f.get("required")==="on"})}}><label className="full"><span>اسم الحقل *</span><input name="label" required /></label><label><span>النوع</span><select name="type"><option value="text">نص</option><option value="number">رقم</option><option value="date">تاريخ</option><option value="textarea">نص طويل</option></select></label><label><span>العرض</span><select name="width"><option value="half">نصف صف</option><option value="full">صف كامل</option></select></label><label className="full"><span>النص الإرشادي</span><input name="placeholder" /></label><label className="inline-check full"><input type="checkbox" name="required" /> حقل إلزامي</label></BaseDialog>; }
