"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Department = { id: number; name: string; color: string; parentId: number | null; parentName: string | null; supportEnabled: number; isActive: number; jobCount: number };
type JobTitle = { id: number; name: string; departmentId: number; department: string };
type Role = { id: number; name: string; description: string };
type Branch = { id: number; name: string; address: string; primaryPhone: string; secondaryPhone: string; email: string; socialUrl: string; isActive: number; customData: string; employeeCount: number; leadCount: number; callCount: number };
type Classroom = { id: number; branchId: number; branchName: string; name: string; capacity: number; isActive: number; customData: string };
type Track = { id: number; title: string; isActive: number; customData: string };
type Employee = { id: number; fullName: string; email: string; phone: string; status: "active" | "invited" | "disabled"; departmentId: number; jobTitleId: number; roleId: number; branchId: number; department: string; jobTitle: string; role: string; branchName: string };
type Field = { id: number; fieldKey: string; label: string; type: string; placeholder: string; required: number; visible: number; sortOrder: number; width: "full" | "half"; version: number; optionsJson: string };
type Lead = { id: number; fullName: string; primaryPhone: string; secondaryPhone: string; email: string; source: string; campaign: string; interest: string; status: string; priority: string; notes: string; customData: string; assignedEmployeeId: number; assignedEmployee: string; branchId: number; branchName: string; callCount: number; lastCallResult: string | null; lastCallBy: string | null; createdAt: string };
type CallRecord = { id: number; leadId: number | null; phone: string; direction: string; result: string; assignedEmployeeId: number; assignedEmployee: string; leadName: string | null; branchId: number; branchName: string; callAt: string; notes: string };
type Followup = { id: number; leadId: number; leadName: string; leadPhone: string; assignedEmployeeId: number; assignedEmployee: string; branchId: number; branchName: string; scheduledAt: string; channel: string; status: string; priority: string; notes: string; outcome: string; completedAt: string | null; createdAt: string };
type Setup = { departments: Department[]; jobTitles: JobTitle[]; roles: Role[]; employees: Employee[]; branches: Branch[]; classrooms: Classroom[]; tracks: Track[]; fields: Field[]; branchFields: Field[]; classroomFields: Field[]; trackFields: Field[]; leads: Lead[]; calls: CallRecord[]; followups: Followup[]; leadFields: Field[]; callFields: Field[]; leadDetailsFields: Field[]; followupFields: Field[] };
type Tab = "overview" | "departments" | "jobs" | "employees" | "leaves" | "permissions" | "forms" | "settings" | "classes" | "tracks" | "leads" | "inboundCalls" | "followups" | "receivedFollowups" | "callCenterCalls" | "placeholder";
type Dialog = "employee" | "department" | "job" | "field" | "branch" | "lead" | "call" | "leadDetails" | "callResult" | "leadHistory" | "scheduleFollowup" | "completeFollowup" | "rescheduleFollowup" | null;

const emptySetup: Setup = { departments: [], jobTitles: [], roles: [], employees: [], branches: [], classrooms: [], tracks: [], fields: [], branchFields: [], classroomFields: [], trackFields: [], leads: [], calls: [], followups: [], leadFields: [], callFields: [], leadDetailsFields: [], followupFields: [] };
const titles: Record<Tab, [string, string]> = {
  overview: ["Dashboard", "نظرة شاملة على نشاط الفروع والمبيعات وخدمة العملاء"], departments: ["أقسام الشركة", "الأقسام الرئيسية والفرعية التي تظهر في نموذج الموظف"], jobs: ["الأدوار الوظيفية", "كل قسم وتحته الوظائف المتاحة داخله"], employees: ["الموظفون", "بيانات الموظفين وحساباتهم على النظام"], leaves: ["الإجازات", "أنواع الإجازات وسياسات الاستحقاق"], permissions: ["الصلاحيات", "صلاحيات الصفحات والإجراءات لكل مجموعة"], forms: ["مصمم النماذج", "تحكم كامل في حقول إدخال بيانات الموظف"],
  leads: ["العملاء المحتملون", "تسجيل وتوزيع الـLeads ومتابعة حالتها الأولية"], inboundCalls: ["المكالمات الواردة", "المكالمات التي استقبلها فريق خدمة العملاء"], callCenterCalls: ["مكالمات الكول سنتر", "سجل المكالمات الواردة والصادرة وربطها بالعملاء"],
  settings: ["Settings", "إدارة بيانات الفروع التي تظهر في الموظفين والعملاء والمكالمات"],
  classes: ["Classes", "إدارة القاعات وسعتها داخل كل فرع"],
  tracks: ["Tracks", "إدارة المسارات التعليمية التي تظهر في بيانات العملاء"],
  followups: ["Leads Followup", "جدولة ومتابعة كل المواعيد القادمة مع العملاء"], receivedFollowups: ["Received Followup", "المتابعات المستحقة والمتأخرة التي تحتاج إجراءً الآن"],
  placeholder: ["Coming Soon", "تمت إضافة الصفحة إلى هيكل النظام وستُفعّل في مرحلتها"],
};

type MenuEntry={label:string;tab?:Tab}; type MenuGroupDefinition={label:string;icon:string;items:MenuEntry[]};
const sidebarGroups:MenuGroupDefinition[]=[
  {label:"Reports",icon:"▥",items:[{label:"Exam Results"},{label:"Oral Results"},{label:"Misplaced Report"},{label:"Retention Report"},{label:"Retention Status"},{label:"Retention Dashboard"},{label:"Students Status"},{label:"Marketing Expenses"},{label:"Total Offers"},{label:"Marketing Masseges"},{label:"LIC-Sales MTD"},{label:"Leads Reports"},{label:"Calls Reports"}]},
  {label:"Settings",icon:"⚙",items:[{label:"Locations",tab:"settings"},{label:"Classes",tab:"classes"},{label:"Tracks",tab:"tracks"},{label:"Time System"},{label:"Rounds"},{label:"Study Types"},{label:"Levels"},{label:"Education Batches"},{label:"Groups"},{label:"Employees Previliges",tab:"permissions"},{label:"Admin Settings",tab:"forms"},{label:"Setup Cards"}]},
  {label:"Exams Manager",icon:"▤",items:[{label:"Exams"},{label:"Questions"},{label:"Instructions"}]},
  {label:"Quizzes Manager",icon:"?",items:[{label:"Quizzes"},{label:"Quizzes Questions"},{label:"Quizzes Instructions"}]},
  {label:"Content Manager",icon:"▣",items:[{label:"Extra Content"},{label:"Student Books"},{label:"Material Audios"},{label:"Material Videos"},{label:"Videos Questions"}]},
  {label:"Books Inventory",icon:"▧",items:[{label:"Stock Items"},{label:"Movements"},{label:"Branch Stock"}]},
  {label:"Customer Care",icon:"☎",items:[{label:"Leads",tab:"leads"},{label:"Inbound calls",tab:"inboundCalls"},{label:"Leads Followup",tab:"followups"},{label:"Received Followup",tab:"receivedFollowups"},{label:"Call Center Calls",tab:"callCenterCalls"},{label:"Support Tickets"},{label:"Recommendation"},{label:"Chat Boxes"}]},
  {label:"Students",icon:"♙",items:[{label:"Profile"},{label:"Students List"},{label:"Attendance"},{label:"Absence Report"},{label:"Placement Test"},{label:"Complaints"},{label:"Informations"}]},
  {label:"Employees Manager",icon:"≡",items:[{label:"Departments",tab:"departments"},{label:"Roles",tab:"jobs"},{label:"Leaves",tab:"leaves"},{label:"Employees",tab:"employees"}]},
  {label:"Supervions",icon:"◉",items:[{label:"Cards"},{label:"Rating Teachers"},{label:"Admin Calls"},{label:"Frontdesk Calls"},{label:"Admin Performance"},{label:"Frontdesk Performance"},{label:"Debtors Calls"},{label:"Visitors Calls"},{label:"Missing Calls"},{label:"NotRegistered Calls"},{label:"Remaining Calls"}]},
  {label:"Financial Dep.",icon:"£",items:[{label:"Offers"},{label:"Payment Methods"},{label:"Payments"},{label:"Debtors"},{label:"Debts Reset"},{label:"Expenses"},{label:"Refunds"}]},
];

export function CrmShell() {
  const [tab, setTab] = useState<Tab>("overview"); const [data, setData] = useState<Setup>(emptySetup); const [loading, setLoading] = useState(true); const [dialog, setDialog] = useState<Dialog>(null); const [notice, setNotice] = useState("");
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [selectedBranch, setSelectedBranch] = useState<Branch | null>(null);
  const [selectedFollowup, setSelectedFollowup] = useState<Followup | null>(null);
  const [plannedPage,setPlannedPage]=useState({group:"",label:""});
  async function load() { const [setupResponse, salesResponse] = await Promise.all([fetch("/api/setup", { cache: "no-store" }), fetch("/api/leads", { cache: "no-store" })]); const setup = await setupResponse.json(); const sales = await salesResponse.json(); if (!setupResponse.ok) throw new Error(setup.error || "تعذر تحميل البيانات"); if (!salesResponse.ok) throw new Error(sales.error || "تعذر تحميل العملاء"); setData({ ...setup, ...sales }); }
  useEffect(() => { load().catch((error) => setNotice(error.message)).finally(() => setLoading(false)); }, []);
  async function mutate(payload: Record<string, unknown>) { const response = await fetch("/api/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); }
  async function mutateSales(payload: Record<string, unknown>) { const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر الحفظ"); await load(); return result; }
  const [title, subtitle] = tab === "placeholder" ? [plannedPage.label || "Coming Soon", `${plannedPage.group} · تمت إضافة الصفحة إلى هيكل النظام`] : titles[tab];
  return <main className="app-shell" dir="rtl">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">م</span><div><strong>مسار</strong><small>إدارة علاقات العملاء</small></div></div>
      <nav aria-label="التنقل الرئيسي">
        <NavItem active={tab === "overview"} icon="▦" label="Dashboard" onClick={() => setTab("overview")} />
        <div className="nav-separator" />
        {sidebarGroups.map((group)=><MenuGroup key={group.label} group={group} tab={tab} plannedPage={plannedPage} onSelect={(entry)=>{if(entry.tab){setTab(entry.tab)}else{setPlannedPage({group:group.label,label:entry.label});setTab("placeholder")}}} badges={{"Leads Followup":data.followups.filter((followup)=>followup.status==="pending").length,"Received Followup":data.followups.filter((followup)=>followup.status==="pending"&&new Date(followup.scheduledAt).getTime()<=Date.now()).length}} />)}
      </nav>
      <div className="phase-card"><span>المرحلة الحالية</span><strong>03 — المتابعات</strong><div className="progress phase-three"><i /></div><small>جدولة المواعيد، تنبيه المستحق وحفظ النتيجة</small></div>
      <div className="profile"><span className="avatar">أم</span><div><strong>أحمد منصور</strong><small>مدير النظام</small></div><button>•••</button></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">مسار CRM <b>/</b> {["leads","inboundCalls","followups","receivedFollowups","callCenterCalls"].includes(tab) ? "Customer Care" : ["settings","classes","tracks"].includes(tab) ? "Settings" : "الموارد البشرية"}</span><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div><div className="top-actions"><button className="icon-button">♢<i /></button>{tab === "departments" && <button className="primary" onClick={() => setDialog("department")}>＋ إضافة قسم</button>}{tab === "jobs" && <button className="primary" onClick={() => setDialog("job")}>＋ إضافة وظيفة</button>}{tab === "employees" && <button className="primary" onClick={() => setDialog("employee")}>＋ إضافة موظف</button>}{tab === "forms" && <button className="primary" onClick={() => setDialog("field")}>＋ إضافة حقل</button>}{tab === "settings" && <button className="primary" onClick={() => { setSelectedBranch(null); setDialog("branch"); }}>＋ إضافة فرع</button>}{tab === "leads" && <button className="primary" onClick={() => setDialog("lead")}>＋ تسجيل Lead</button>}{(tab === "inboundCalls" || tab === "callCenterCalls") && <button className="primary" onClick={() => setDialog("call")}>＋ تسجيل مكالمة</button>}</div></header>
      {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {loading ? <Loading /> : <Page tab={tab} data={data} plannedPage={plannedPage} mutate={mutate} open={setDialog} setNotice={setNotice} addBranch={() => { setSelectedBranch(null); setDialog("branch"); }} selectLead={(lead, next) => { setSelectedLead(lead); setDialog(next); }} selectFollowup={(followup, next) => { setSelectedFollowup(followup); setDialog(next); }} editBranch={(branch) => { setSelectedBranch(branch); setDialog("branch"); }} />}
    </section>
    {dialog === "employee" && <EmployeeDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createEmployee", ...payload }); setDialog(null); setNotice("تم إنشاء حساب الموظف وإضافة ملفه بنجاح"); }} />}
    {dialog === "department" && <DepartmentDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createDepartment", ...payload }); setDialog(null); setNotice("تمت إضافة القسم وسيظهر الآن في نموذج الموظف"); }} />}
    {dialog === "job" && <JobDialog departments={data.departments} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "createJobTitle", ...payload }); setDialog(null); setNotice("تمت إضافة الوظيفة تحت القسم المحدد"); }} />}
    {dialog === "field" && <FieldDialog onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutate({ action: "addField", ...payload }); setDialog(null); setNotice("تمت إضافة الحقل للنموذج المحدد"); }} />}
    {dialog === "branch" && <BranchDialog data={data} branch={selectedBranch} onClose={() => { setDialog(null); setSelectedBranch(null); }} onSubmit={async (payload) => { const wasEditing=Boolean(selectedBranch); const standard=new Set(["name","address","primaryPhone","secondaryPhone","email","socialUrl","isActive"]); let existing:Record<string,unknown>={}; try{existing=selectedBranch?JSON.parse(selectedBranch.customData||"{}"):{};}catch{existing={};} const customData={...existing,...Object.fromEntries(Object.entries(payload).filter(([key])=>!standard.has(key)))}; await mutate({ action: wasEditing ? "updateBranch" : "createBranch", id: selectedBranch?.id, ...payload, customData }); setDialog(null); setSelectedBranch(null); setNotice(wasEditing ? "تم تحديث بيانات الفرع في كل أجزاء النظام" : "تمت إضافة الفرع بدون تغيير الفروع الحالية"); }} />}
    {dialog === "lead" && <LeadDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "createLead", ...payload }); setDialog(null); setNotice("تم تسجيل العميل المحتمل وتعيين الموظف المسؤول"); }} />}
    {dialog === "call" && <CallDialog data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { const result = await mutateSales({ action: "createCall", ...payload }); setDialog(null); setNotice(result.matchedLead ? "تم تسجيل المكالمة وربطها بالعميل الموجود" : "تم تسجيل المكالمة كرقم غير مرتبط بعميل"); }} />}
    {dialog === "leadDetails" && selectedLead && <LeadDetailsDialog lead={selectedLead} fields={data.leadDetailsFields} data={data} onClose={() => setDialog(null)} onSubmit={async (details) => { await mutateSales({ action: "updateLeadDetails", id: selectedLead.id, details }); setDialog(null); setNotice("تم استكمال بيانات العميل"); }} />}
    {dialog === "callResult" && selectedLead && <LeadCallResultDialog lead={selectedLead} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "recordLeadCallResult", id: selectedLead.id, ...payload }); setDialog(null); setNotice("تم حفظ نتيجة المكالمة وإضافتها إلى السجل"); }} />}
    {dialog === "leadHistory" && selectedLead && <LeadHistoryDialog lead={selectedLead} calls={data.calls.filter((call) => call.leadId === selectedLead.id)} onClose={() => setDialog(null)} />}
    {dialog === "scheduleFollowup" && selectedLead && <FollowupDialog lead={selectedLead} data={data} onClose={() => setDialog(null)} onSubmit={async (payload) => { await mutateSales({ action: "createFollowup", leadId: selectedLead.id, ...payload }); setDialog(null); setNotice("تمت جدولة المتابعة وإضافتها لقائمة المسؤول"); }} />}
    {dialog === "completeFollowup" && selectedFollowup && <CompleteFollowupDialog followup={selectedFollowup} onClose={() => setDialog(null)} onSubmit={async (outcome) => { await mutateSales({ action: "completeFollowup", id: selectedFollowup.id, outcome }); setDialog(null); setNotice("تم إنهاء المتابعة وحفظ نتيجتها"); }} />}
    {dialog === "rescheduleFollowup" && selectedFollowup && <RescheduleDialog followup={selectedFollowup} onClose={() => setDialog(null)} onSubmit={async (scheduledAt) => { await mutateSales({ action: "rescheduleFollowup", id: selectedFollowup.id, scheduledAt }); setDialog(null); setNotice("تم تعديل موعد المتابعة"); }} />}
  </main>;
}

function Page({ tab, data, plannedPage, mutate, open, setNotice, addBranch, selectLead, selectFollowup, editBranch }: { tab: Tab; data: Setup; plannedPage:{group:string;label:string}; mutate: (p: Record<string, unknown>) => Promise<void>; open: (d: Dialog) => void; setNotice: (s: string) => void; addBranch:()=>void; selectLead: (lead: Lead, dialog: Dialog) => void; selectFollowup: (followup: Followup, dialog: Dialog) => void; editBranch: (branch: Branch) => void }) {
  if (tab === "overview") return <DashboardPage data={data} go={open} />;
  if (tab === "departments") return <Departments data={data} add={() => open("department")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "jobs") return <Jobs data={data} add={() => open("job")} mutate={mutate} setNotice={setNotice} />;
  if (tab === "employees") return <Employees data={data} add={() => open("employee")} />;
  if (tab === "leaves") return <Leaves />;
  if (tab === "permissions") return <Permissions roles={data.roles} />;
  if (tab === "settings") return <SettingsPage data={data} add={addBranch} edit={editBranch} mutate={mutate} setNotice={setNotice} />;
  if (tab === "classes") return <ClassesPage data={data} mutate={mutate} setNotice={setNotice} />;
  if (tab === "tracks") return <TracksPage data={data} mutate={mutate} setNotice={setNotice} />;
  if (tab === "leads") return <LeadsPage data={data} addLead={() => open("lead")} addCall={() => open("call")} onAction={selectLead} />;
  if (tab === "inboundCalls") return <CallsPage data={data} add={() => open("call")} mode="incoming" />;
  if (tab === "followups") return <FollowupsPage data={data} mode="all" onAction={selectFollowup} />;
  if (tab === "receivedFollowups") return <FollowupsPage data={data} mode="due" onAction={selectFollowup} />;
  if (tab === "callCenterCalls") return <CallsPage data={data} add={() => open("call")} mode="all" />;
  if (tab === "placeholder") return <PlannedPage group={plannedPage.group} label={plannedPage.label} />;
  return <FormBuilder fields={data.fields} data={data} mutate={mutate} onAdd={() => open("field")} />;
}

function SubNav({ label, active=false, disabled=false, badge, onClick }: { label: string; active?: boolean; disabled?: boolean; badge?: string; onClick?: () => void }) { return <button className={`${active ? "active" : ""} ${disabled ? "disabled" : ""}`} onClick={onClick} disabled={disabled}><i /><span>{label}</span>{badge && <em>{badge}</em>}</button>; }
function NavItem({ active, disabled, icon, label, badge, onClick }: { active?: boolean; disabled?: boolean; icon: string; label: string; badge?: string; onClick?: () => void }) { return <button className={`nav-item ${active ? "active" : ""} ${disabled ? "disabled" : ""}`} onClick={onClick} disabled={disabled}><span className="nav-icon">{icon}</span><span>{label}</span>{badge && <em>{badge}</em>}</button>; }
function MenuGroup({group,tab,plannedPage,onSelect,badges}:{group:MenuGroupDefinition;tab:Tab;plannedPage:{group:string;label:string};onSelect:(entry:MenuEntry)=>void;badges:Record<string,number>}) { const containsActive=group.items.some((item)=>item.tab===tab)||(tab==="placeholder"&&plannedPage.group===group.label); const [open,setOpen]=useState(group.label==="Customer Care"||group.label==="Employees Manager"||containsActive); useEffect(()=>{if(containsActive)setOpen(true)},[containsActive]); return <div className={`erp-menu-group ${containsActive?"active":""}`}><button className={`nav-group ${containsActive?"active":""}`} onClick={()=>setOpen((value)=>!value)}><span className="nav-icon">{group.icon}</span><span><strong>{group.label}</strong><small>{group.items.length} pages</small></span><b>{open?"⌃":"⌄"}</b></button>{open&&<div className="subnav erp-subnav">{group.items.map((entry)=><SubNav key={entry.label} label={entry.label} active={entry.tab?tab===entry.tab:tab==="placeholder"&&plannedPage.group===group.label&&plannedPage.label===entry.label} badge={badges[entry.label]?String(badges[entry.label]):undefined} onClick={()=>onSelect(entry)}/>)}</div>}</div>; }
function Loading() { return <div className="loading-grid"><div /><div /><div /><article /></div>; }

function PlannedPage({group,label}:{group:string;label:string}) { return <section className="panel planned-page"><div className="planned-orbit"><span>◇</span><i/><i/><i/></div><div><span className="version">{group}</span><h2>{label}</h2><p>الصفحة موجودة الآن في القائمة الجانبية بنفس ترتيب النظام المرجعي، وسيتم توصيل وظائفها وبياناتها في المرحلة الخاصة بها.</p><div className="planned-features"><span>✓ مكانها ثابت في الصلاحيات</span><span>✓ جاهزة للربط بقاعدة البيانات</span><span>✓ متوافقة مع تصميم النظام</span></div></div></section>; }

function HrOverview({ data, go }: { data: Setup; go: (d: Dialog) => void }) {
  return <div className="content-stack"><section className="metrics"><Metric label="الموظفون" value={data.employees.length} hint="ملفات مسجلة" tone="green" /><Metric label="أقسام الشركة" value={data.departments.length} hint="رئيسية وفرعية" tone="blue" /><Metric label="الأدوار الوظيفية" value={data.jobTitles.length} hint="مرتبطة بالأقسام" tone="orange" /><Metric label="حسابات نشطة" value={data.employees.filter((e) => e.status === "active").length} hint="تعمل على النظام" tone="purple" /></section><section className="hr-map"><div className="hr-intro"><span>نظام موارد بشرية مترابط</span><h2>ابدأ بالهيكل، ثم أضف فريقك</h2><p>القسم يحدد الوظائف المتاحة، والوظيفة ومجموعة الصلاحيات تحددان ما يمكن للموظف رؤيته وتنفيذه داخل النظام.</p></div><div className="flow-cards"><FlowCard n="01" title="أقسام الشركة" text="أضف الأقسام الرئيسية والفرعية" /><b>←</b><FlowCard n="02" title="الأدوار الوظيفية" text="عرّف الوظائف داخل كل قسم" /><b>←</b><FlowCard n="03" title="الموظفون" text="أنشئ الملف والحساب والصلاحيات" /></div><div className="quick-row"><button onClick={() => go("department")}>＋ قسم جديد</button><button onClick={() => go("job")}>＋ وظيفة جديدة</button><button onClick={() => go("employee")}>＋ موظف جديد</button></div></section></div>;
}

function DashboardPage({data,go}:{data:Setup;go:(d:Dialog)=>void}) {
  const today=new Date().toISOString().slice(0,10); const monthStart=`${today.slice(0,8)}01`;
  const [from,setFrom]=useState(monthStart); const [to,setTo]=useState(today);
  const inRange=(value:string)=>{const time=new Date(value).getTime();const start=new Date(`${from}T00:00:00`).getTime();const end=new Date(`${to}T23:59:59`).getTime();return time>=start&&time<=end;};
  const leads=data.leads.filter((lead)=>inRange(lead.createdAt)); const calls=data.calls.filter((call)=>inRange(call.callAt)); const followups=data.followups.filter((followup)=>inRange(followup.scheduledAt));
  const pending=followups.filter((followup)=>followup.status==="pending"); const answered=calls.filter((call)=>call.result==="answered"); const incoming=calls.filter((call)=>call.direction==="incoming"); const unlinked=calls.filter((call)=>!call.leadId); const qualified=leads.filter((lead)=>lead.status==="qualified");
  const branchRows=data.branches.map((branch)=>({name:branch.name,leads:leads.filter((lead)=>lead.branchId===branch.id).length,calls:calls.filter((call)=>call.branchId===branch.id).length,followups:followups.filter((followup)=>followup.branchId===branch.id).length,employees:data.employees.filter((employee)=>employee.branchId===branch.id).length}));
  const maxActivity=Math.max(1,...branchRows.flatMap((row)=>[row.leads,row.calls]));
  const callResults=[{label:"Answered",value:answered.length,color:"#55a88e"},{label:"No Answer",value:calls.filter((call)=>call.result==="no_answer").length,color:"#ef9a62"},{label:"Callback",value:calls.filter((call)=>call.result==="callback").length,color:"#7367f0"},{label:"Busy",value:calls.filter((call)=>call.result==="busy").length,color:"#6aa8d8"}]; const maxResult=Math.max(1,...callResults.map((item)=>item.value));
  const leadStatuses=["new","contacted","followup","qualified","unqualified"].map((status)=>({status,count:leads.filter((lead)=>lead.status===status).length}));
  return <div className="erp-dashboard" dir="ltr">
    <section className="dashboard-filter"><div><strong>Dashboard</strong><span>Live business overview</span></div><label>From<input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={(event)=>setTo(event.target.value)}/></label><button onClick={()=>{setFrom(today);setTo(today)}}>Today</button><button className="dashboard-filter-month" onClick={()=>{setFrom(monthStart);setTo(today)}}>This Month</button></section>
    <section className="dashboard-stat-grid"><DashboardStat label="Branch Visitors" value={incoming.length} icon="⌂" tone="purple"/><DashboardStat label="Online Calls" value={calls.length} icon="☎" tone="blue"/><DashboardStat label="New Members" value={qualified.length} icon="♙" tone="green"/><DashboardStat label="Income" value="0 EGP" icon="£" tone="orange"/><DashboardStat label="Not Registered" value={unlinked.length} icon="?" tone="red"/><DashboardStat label="Follow Ups" value={pending.length} icon="◷" tone="purple"/><DashboardStat label="Retention" value={qualified.length} icon="↻" tone="blue"/><DashboardStat label="Refunds" value={0} icon="↩" tone="orange"/></section>
    <section className="dashboard-mini-grid"><DashboardStat label="Admin Retention Calls" value={calls.filter((call)=>call.result==="callback").length} compact/><DashboardStat label="Admin Absence Calls" value={calls.filter((call)=>call.result==="no_answer").length} compact/><DashboardStat label="Admin Debtor Calls" value={0} compact/><DashboardStat label="Admin Remaining Calls" value={pending.length} compact/><DashboardStat label="Frontdesk Visitors Calls" value={incoming.length} compact/><DashboardStat label="Frontdesk Debtors Calls" value={0} compact/><DashboardStat label="Frontdesk NotReg Calls" value={unlinked.length} compact/><DashboardStat label="Frontdesk Missing Calls" value={calls.filter((call)=>call.result==="wrong_number").length} compact/></section>
    <section className="dashboard-wide-stats"><DashboardStat label="Total Leads" value={leads.length} icon="◇" tone="purple"/><DashboardStat label="Lead Answer Calls" value={answered.length} icon="✓" tone="green"/><DashboardStat label="Total Expenses" value="0 EGP" icon="−" tone="red"/></section>
    <section className="dashboard-card dashboard-income"><DashboardSectionHead title="Branches Income" total="0 EGP"/><div className="dashboard-card-body dashboard-chart-layout"><div className="dashboard-bars"><div className="chart-legend"><span><i className="legend-leads"/>Leads</span><span><i className="legend-calls"/>Calls</span></div>{branchRows.map((row)=><div className="bar-row" key={row.name}><strong>{row.name}</strong><div><i className="bar-leads" style={{width:`${Math.max(3,row.leads/maxActivity*100)}%`}}><span>{row.leads}</span></i><i className="bar-calls" style={{width:`${Math.max(3,row.calls/maxActivity*100)}%`}}><span>{row.calls}</span></i></div></div>)}</div><div className="income-summary"><h3>Activity Details</h3><p><span>New Members</span><b>{qualified.length}</b></p><p><span>Follow Ups</span><b>{followups.length}</b></p><p><span>Incoming Calls</span><b>{incoming.length}</b></p><p><span>Total Income</span><b>0 EGP</b></p></div></div></section>
    <section className="dashboard-card"><DashboardSectionHead title="Income Details" total="0 EGP"/><div className="table-wrap"><table className="dashboard-table"><thead><tr><th>Branch</th><th>New Members</th><th>Leads</th><th>Calls</th><th>Follow Ups</th><th>Income</th></tr></thead><tbody>{branchRows.map((row)=><tr key={row.name}><td><strong>{row.name}</strong></td><td>{row.leads?qualified.filter((lead)=>lead.branchName===row.name).length:0}</td><td>{row.leads}</td><td>{row.calls}</td><td>{row.followups}</td><td>0 EGP</td></tr>)}</tbody></table></div></section>
    <section className="dashboard-card"><DashboardSectionHead title="Branch / Batch Details"/><div className="table-wrap"><table className="dashboard-table"><thead><tr><th>Branch</th><th>Employees</th><th>Leads</th><th>Calls</th><th>Pending Follow Ups</th><th>Batches</th></tr></thead><tbody>{branchRows.map((row)=><tr key={row.name}><td><strong>{row.name}</strong></td><td>{row.employees}</td><td>{row.leads}</td><td>{row.calls}</td><td>{pending.filter((followup)=>followup.branchName===row.name).length}</td><td><span className="planned-chip">Phase 5</span></td></tr>)}</tbody></table></div></section>
    <section className="dashboard-card"><DashboardSectionHead title="Report Of Card System For This Month"/><div className="status-report">{leadStatuses.map((item)=><article key={item.status}><LeadStatus value={item.status}/><strong>{item.count}</strong><small>Leads</small></article>)}</div></section>
    <section className="dashboard-card"><DashboardSectionHead title="Absence / Calls / Complains Reports"/><div className="dashboard-dual-chart"><div><h3>Calls / Leads by Branch</h3>{branchRows.map((row)=><div className="compare-row" key={row.name}><span>{row.name}</span><div><i style={{width:`${row.calls/maxActivity*100}%`}}/><b style={{width:`${row.leads/maxActivity*100}%`}}/></div><em>{row.calls} / {row.leads}</em></div>)}</div><div><h3>Call Results</h3>{callResults.map((item)=><div className="result-bar" key={item.label}><span>{item.label}</span><div><i style={{width:`${item.value/maxResult*100}%`,background:item.color}}/></div><b>{item.value}</b></div>)}</div></div></section>
    <section className="dashboard-bottom-grid"><article className="dashboard-card"><DashboardSectionHead title="Debtors This Month"/><div className="future-module"><span>◎</span><h3>No debtor records yet</h3><p>This report will activate with the payments stage.</p></div></article><article className="dashboard-card"><DashboardSectionHead title="Payment Methods Details"/><div className="payment-placeholder"><i/><i/><i/><i/><p>Payment methods will appear after Phase 4.</p></div></article></section>
    <div className="dashboard-quick"><button onClick={()=>go("lead")}>＋ New Lead</button><button onClick={()=>go("call")}>☎ New Call</button></div>
  </div>;
}

function DashboardStat({label,value,icon="•",tone="neutral",compact=false}:{label:string;value:number|string;icon?:string;tone?:string;compact?:boolean}) { return <article className={`dashboard-stat ${compact?"compact":""}`}><span className={`dashboard-stat-icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function DashboardSectionHead({title,total}:{title:string;total?:string}) { return <header className="dashboard-section-head"><h2>{title}{total&&<b>{total}</b>}</h2><button title="Refresh">↻</button></header>; }
function FlowCard({ n, title, text }: { n: string; title: string; text: string }) { return <article><span>{n}</span><strong>{title}</strong><small>{text}</small></article>; }

function Departments({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteDepartment", id }); setNotice("تم حذف القسم"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <section className="panel"><div className="panel-head"><div><h2>قائمة أقسام الشركة</h2><p>الأقسام هنا هي المصدر المباشر لقائمة القسم داخل نموذج الموظف.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث عن قسم..." /></label><button className="secondary" onClick={add}>＋ إضافة جديد</button></div></div><div className="table-wrap"><table className="departments-table"><thead><tr><th>#</th><th>اسم القسم</th><th>القسم الرئيسي</th><th>الدعم</th><th>عدد الوظائف</th><th>الإجراءات</th></tr></thead><tbody>{data.departments.map((d, i) => <tr key={d.id}><td>{i + 1}</td><td><strong className="dept-title"><i style={{ background: d.color }} />{d.name}</strong></td><td>{d.parentName ? <span>{d.parentName}</span> : <span className="tag no-parent">بدون قسم رئيسي</span>}</td><td>{d.supportEnabled ? <span className="tag support">مفعّل</span> : <span className="tag off">غير مفعّل</span>}</td><td><span className="count-chip">{d.jobCount} وظائف</span></td><td><div className="actions"><button className="edit">تعديل</button><button className="delete" onClick={() => remove(d.id)}>حذف</button></div></td></tr>)}</tbody></table></div></section>;
}

function Jobs({ data, add, mutate, setNotice }: { data: Setup; add: () => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  async function remove(id: number) { try { await mutate({ action: "deleteJobTitle", id }); setNotice("تم حذف الوظيفة"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر الحذف"); } }
  return <div className="jobs-layout"><div className="jobs-toolbar"><p>كل وظيفة مرتبطة بقسم واحد، وتظهر للموظف بعد اختيار القسم.</p><button className="secondary" onClick={add}>＋ إضافة وظيفة</button></div><div className="department-groups">{data.departments.map((department) => { const jobs = data.jobTitles.filter((job) => job.departmentId === department.id); return <section className="job-group" key={department.id}><header><span style={{ background: department.color }}>{initials(department.name)}</span><div><h2>{department.name}</h2><p>{jobs.length} أدوار وظيفية</p></div><button onClick={add}>＋</button></header><div>{jobs.length ? jobs.map((job) => <article key={job.id}><div><strong>{job.name}</strong><small>يتبع قسم {department.name}</small></div><button className="row-menu">تعديل</button><button className="row-menu danger" onClick={() => remove(job.id)}>حذف</button></article>) : <p className="empty-line">لا توجد وظائف داخل هذا القسم بعد.</p>}</div></section>; })}</div></div>;
}

function SettingsPage({ data, add, edit, mutate, setNotice }: { data: Setup; add: () => void; edit: (branch: Branch) => void; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  const [query,setQuery]=useState("");
  async function remove(branch: Branch) { try { await mutate({ action: "deleteBranch", id: branch.id }); setNotice("تم حذف الفرع"); } catch (e) { setNotice(e instanceof Error ? e.message : "تعذر حذف الفرع"); } }
  const branches=data.branches.filter((branch)=>`${branch.name} ${branch.address} ${branch.primaryPhone}`.toLowerCase().includes(query.trim().toLowerCase())); const active=data.branches.filter((branch)=>branch.isActive).length; const employees=data.branches.reduce((sum,branch)=>sum+Number(branch.employeeCount),0);
  return <div className="locations-page"><section className="locations-hero"><div className="locations-hero-copy"><span>LOCATIONS DIRECTORY</span><h2>شبكة فروع مسار</h2><p>مصدر واحد للفروع ينعكس تلقائيًا في الموظفين والـLeads والمكالمات.</p></div><div className="location-kpis"><span><b>{data.branches.length}</b> إجمالي</span><span><b>{active}</b> نشط</span><span><b>{employees}</b> موظف</span></div><button onClick={add}>＋ فرع جديد</button></section><section className="locations-toolbar"><label><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث بالاسم أو العنوان أو الهاتف..."/></label><span>{branches.length} نتيجة</span></section>{branches.length?<section className="location-grid">{branches.map((branch)=><article className="location-card" key={branch.id}><header><div className="location-mark">{initials(branch.name)}</div><div><h3>{branch.name}</h3><span className={`branch-state ${branch.isActive?"active":"inactive"}`}>{branch.isActive?"نشط":"غير نشط"}</span></div><div className="location-menu"><button onClick={()=>edit(branch)} title="تعديل">✎</button><button className="danger" onClick={()=>remove(branch)} title="حذف">×</button></div></header><p className="location-address">⌖ {branch.address}</p><div className="location-lines"><a href={`tel:${branch.primaryPhone}`}>☎ <span>{branch.primaryPhone}</span></a>{branch.email&&<a href={`mailto:${branch.email}`}>✉ <span>{branch.email}</span></a>}{branch.socialUrl&&<a href={branch.socialUrl} target="_blank" rel="noreferrer">↗ <span>صفحة التواصل</span></a>}</div><footer><span><b>{branch.employeeCount}</b> موظف</span><span><b>{branch.leadCount}</b> Lead</span><span><b>{branch.callCount}</b> مكالمة</span></footer></article>)}</section>:<div className="empty locations-empty"><span>⌕</span><h3>لا توجد نتائج</h3><p>غيّر كلمة البحث أو أضف فرعًا جديدًا.</p><button className="primary" onClick={add}>＋ فرع جديد</button></div>}</div>;
}

function ClassesPage({ data, mutate, setNotice }: { data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; setNotice: (s: string) => void }) {
  const [query,setQuery]=useState("");
  const [branchFilter,setBranchFilter]=useState("");
  const [selected,setSelected]=useState<Classroom|null>(null);
  const [editorOpen,setEditorOpen]=useState(false);
  const normalized=query.trim().toLowerCase();
  const rows=data.classrooms.filter((room)=>(!branchFilter||room.branchId===Number(branchFilter))&&`${room.name} ${room.branchName}`.toLowerCase().includes(normalized));
  const totalSeats=data.classrooms.reduce((sum,room)=>sum+Number(room.capacity),0);
  async function remove(room:Classroom){if(!window.confirm(`حذف ${room.name} من ${room.branchName}؟`))return;try{await mutate({action:"deleteClassroom",id:room.id});setNotice("تم حذف القاعة")}catch(error){setNotice(error instanceof Error?error.message:"تعذر حذف القاعة")}}
  return <div className="classes-page"><section className="classes-summary"><div><span>CLASSES DIRECTORY</span><h2>القاعات والفصول</h2><p>كل قاعة مرتبطة بفرع واحد، مع السعة والحالة في مصدر بيانات موحّد.</p></div><div className="class-kpis"><span><b>{data.classrooms.length}</b> قاعة</span><span><b>{data.classrooms.filter((room)=>room.isActive).length}</b> نشطة</span><span><b>{totalSeats}</b> مقعد</span></div><button className="primary" onClick={()=>{setSelected(null);setEditorOpen(true)}}>＋ إضافة Class</button></section><section className="classes-toolbar"><label className="search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث باسم القاعة أو الفرع..."/></label><select value={branchFilter} onChange={(event)=>setBranchFilter(event.target.value)}><option value="">كل الفروع</option>{data.branches.map((branch)=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><span>{rows.length} نتيجة</span></section><section className="panel class-list-panel">{rows.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>الفرع</th><th>اسم القاعة</th><th>السعة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{rows.map((room,index)=><tr key={room.id}><td>{index+1}</td><td><span className="class-branch">⌖ {room.branchName}</span></td><td><strong>{room.name}</strong></td><td><span className="capacity-chip"><b>{room.capacity}</b> طالب</span></td><td><span className={`branch-state ${room.isActive?"active":"inactive"}`}>{room.isActive?"نشط":"غير نشط"}</span></td><td><div className="actions"><button className="edit" onClick={()=>{setSelected(room);setEditorOpen(true)}}>تعديل</button><button className="delete" onClick={()=>remove(room)}>حذف</button></div></td></tr>)}</tbody></table></div>:<div className="empty"><span>▦</span><h3>لا توجد قاعات</h3><p>أضف أول قاعة وحدد الفرع والسعة.</p><button className="primary" onClick={()=>{setSelected(null);setEditorOpen(true)}}>＋ إضافة Class</button></div>}</section>{editorOpen&&<ClassroomDialog data={data} room={selected} onClose={()=>{setEditorOpen(false);setSelected(null)}} onSubmit={async(values)=>{const standard=new Set(["name","branchId","capacity","isActive"]);let existing:Record<string,unknown>={};try{existing=selected?JSON.parse(selected.customData||"{}"):{};}catch{existing={}}const customData={...existing,...Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)))};await mutate({action:selected?"updateClassroom":"createClassroom",id:selected?.id,...values,customData});setEditorOpen(false);setSelected(null);setNotice(selected?"تم تحديث بيانات القاعة":"تمت إضافة القاعة بنجاح")}}/>}</div>;
}

function TracksPage({data,mutate,setNotice}:{data:Setup;mutate:(p:Record<string,unknown>)=>Promise<void>;setNotice:(s:string)=>void}) {
  const [query,setQuery]=useState("");const [selected,setSelected]=useState<Track|null>(null);const [editorOpen,setEditorOpen]=useState(false);const rows=data.tracks.filter((track)=>track.title.toLowerCase().includes(query.trim().toLowerCase()));
  async function remove(track:Track){if(!window.confirm(`حذف ${track.title}؟`))return;try{await mutate({action:"deleteTrack",id:track.id});setNotice("تم حذف الـTrack")}catch(error){setNotice(error instanceof Error?error.message:"تعذر حذف الـTrack")}}
  return <div className="tracks-page"><section className="tracks-hero"><div><span>LEARNING TRACKS</span><h2>المسارات التعليمية</h2><p>قائمة موحّدة تظهر تلقائيًا عند تسجيل اهتمام العميل داخل الـLeads.</p></div><div className="track-kpis"><span><b>{data.tracks.length}</b> إجمالي</span><span><b>{data.tracks.filter((track)=>track.isActive).length}</b> نشط</span><span><b>{data.tracks.filter((track)=>!track.isActive).length}</b> متوقف</span></div><button className="primary" onClick={()=>{setSelected(null);setEditorOpen(true)}}>＋ إضافة Track</button></section><section className="tracks-toolbar"><label className="search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث باسم الـTrack..."/></label><span>{rows.length} نتيجة</span></section><section className="track-grid">{rows.map((track,index)=><article className="track-card" key={track.id}><div className="track-number">{String(index+1).padStart(2,"0")}</div><div className="track-symbol">◇</div><div><h3>{track.title}</h3><span className={`branch-state ${track.isActive?"active":"inactive"}`}>{track.isActive?"نشط":"غير نشط"}</span></div><div className="track-actions"><button onClick={()=>{setSelected(track);setEditorOpen(true)}}>تعديل</button><button className="danger" onClick={()=>remove(track)}>حذف</button></div></article>)}</section>{!rows.length&&<section className="panel empty"><span>◇</span><h3>لا توجد Tracks</h3><p>أضف أول مسار ليظهر في نماذج النظام.</p><button className="primary" onClick={()=>{setSelected(null);setEditorOpen(true)}}>＋ إضافة Track</button></section>}{editorOpen&&<TrackDialog data={data} track={selected} onClose={()=>{setEditorOpen(false);setSelected(null)}} onSubmit={async(values)=>{const standard=new Set(["title","isActive"]);let existing:Record<string,unknown>={};try{existing=selected?JSON.parse(selected.customData||"{}"):{};}catch{existing={}}const customData={...existing,...Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)))};await mutate({action:selected?"updateTrack":"createTrack",id:selected?.id,...values,customData});setEditorOpen(false);setSelected(null);setNotice(selected?"تم تحديث الـTrack":"تمت إضافة الـTrack بنجاح")}}/>}</div>;
}

function Employees({ data, add }: { data: Setup; add: () => void }) {
  const active = data.employees.filter((e) => e.status === "active").length;
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي الموظفين" value={data.employees.length} hint="كل الملفات" tone="green" /><Metric label="الحسابات النشطة" value={active} hint="جاهزة للعمل" tone="blue" /><Metric label="دعوات معلقة" value={data.employees.filter((e) => e.status === "invited").length} hint="في انتظار التفعيل" tone="orange" /><Metric label="الأقسام" value={data.departments.length} hint="هيكل الشركة" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>دليل الموظفين</h2><p>ملف الموظف، الفرع، القسم، الدور الوظيفي، وصلاحيات النظام.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو البريد..." /></label><button className="secondary" onClick={add}>＋ موظف جديد</button></div></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>الفرع</th><th>القسم</th><th>الدور الوظيفي</th><th>الصلاحيات</th><th>الحالة</th><th /></tr></thead><tbody>{data.employees.map((e) => <tr key={e.id}><td><div className="employee"><span>{initials(e.fullName)}</span><div><strong>{e.fullName}</strong><small>{e.email}</small></div></div></td><td>{e.branchName || "—"}</td><td><span className="department-dot" style={{ background: data.departments.find((d) => d.id === e.departmentId)?.color }} />{e.department}</td><td>{e.jobTitle}</td><td><span className="role-chip">{e.role}</span></td><td><Status status={e.status} /></td><td><button className="row-menu">•••</button></td></tr>)}</tbody></table></div><div className="table-footer"><span>عرض {data.employees.length} موظفين</span><button className="primary" onClick={add}>＋ إضافة موظف</button></div></section></div>;
}

function Leaves() { return <section className="panel leaves-panel"><div className="panel-head"><div><h2>أنواع الإجازات</h2><p>الجزء ظاهر داخل الموارد البشرية، وسيتم تفعيل سياساته عند اعتماد متطلبات الإجازات.</p></div><span className="tag support">مخطط</span></div><div className="leave-grid"><article><span>سنوية</span><strong>21 يوم</strong><small>الرصيد الافتراضي</small></article><article><span>عارضة</span><strong>6 أيام</strong><small>ضمن الرصيد السنوي</small></article><article><span>مرضية</span><strong>حسب اللائحة</strong><small>تحتاج مستندًا</small></article></div><div className="guard-note"><span>◈</span><div><strong>لم يتم تفعيل عمليات الإجازات بعد</strong><p>سنحدد دورة الطلب والموافقة والأرصدة في خطوة مستقلة حتى لا نفترض سياسة غير معتمدة.</p></div></div></section>; }

function Permissions({ roles }: { roles: Role[] }) { const rows = ["الموظفون", "الأقسام والوظائف", "إعدادات النماذج", "العملاء المحتملون"]; return <div className="split-layout"><section className="panel roles-list"><div className="panel-head"><div><h2>مجموعات الصلاحيات</h2><p>صلاحيات استخدام النظام، وليست الدور الوظيفي.</p></div><button className="secondary">＋ مجموعة جديدة</button></div>{roles.map((role, i) => <button key={role.id} className={`role-row ${i === 0 ? "selected" : ""}`}><span className="role-symbol">{i === 0 ? "♛" : "◆"}</span><div><strong>{role.name}</strong><small>{role.description}</small></div></button>)}</section><section className="panel permission-matrix"><div className="panel-head"><div><span className="mini-label">صلاحيات المجموعة</span><h2>مدير النظام</h2></div><button className="primary">حفظ التغييرات</button></div><table><thead><tr><th>الصفحة</th><th>عرض</th><th>إضافة</th><th>تعديل</th><th>حذف</th></tr></thead><tbody>{rows.map((row, ri) => <tr key={row}><td><strong>{row}</strong></td>{[0,1,2,3].map((c) => <td key={c}><label className="check"><input type="checkbox" defaultChecked={ri < 3 || c < 2} /><span>✓</span></label></td>)}</tr>)}</tbody></table></section></div>; }

function FormBuilder({ fields: initialFields, data, mutate, onAdd }: { fields: Field[]; data: Setup; mutate: (p: Record<string, unknown>) => Promise<void>; onAdd: () => void }) {
  const formOptions=[{key:"employee",name:"الموظف",fields:initialFields},{key:"branch",name:"الفرع",fields:data.branchFields},{key:"classroom",name:"القاعة",fields:data.classroomFields},{key:"track",name:"الـTrack",fields:data.trackFields},{key:"lead",name:"Lead جديدة",fields:data.leadFields},{key:"call",name:"المكالمة",fields:data.callFields},{key:"lead_details",name:"استكمال العميل",fields:data.leadDetailsFields},{key:"followup",name:"المتابعة",fields:data.followupFields}];
  const [formKey,setFormKey]=useState("employee"); const [saving, setSaving] = useState<number | null>(null); const selected=formOptions.find((form)=>form.key===formKey)||formOptions[0]; const fields=selected.fields; const previewFields=fields.filter((f)=>f.visible).slice(0,8);
  return <div className="builder-layout"><section className="panel field-panel"><div className="panel-head"><div><span className="version">نسخة {fields[0]?.version ?? 1}</span><h2>نموذج {selected.name}</h2><p>{fields.length} حقلًا قابلًا للتحكم من هنا.</p></div><div className="form-builder-actions"><select value={formKey} onChange={(e)=>setFormKey(e.target.value)}>{formOptions.map((form)=><option key={form.key} value={form.key}>{form.name}</option>)}</select><button className="secondary" onClick={onAdd}>＋ حقل جديد</button></div></div><div className="field-list">{fields.map((f, i) => <div className={`field-row ${!f.visible ? "muted" : ""}`} key={f.id}><span className="drag">⠿</span><span className="field-index">{String(i + 1).padStart(2,"0")}</span><div className="field-info"><strong>{f.label}</strong><small>{f.fieldKey} · {f.type}</small></div><label className="mini-toggle"><input type="checkbox" checked={!!f.required} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:!!f.visible, required:e.target.checked }); setSaving(null); }} /><span />إلزامي</label><label className="mini-toggle"><input type="checkbox" checked={!!f.visible} onChange={async (e) => { setSaving(f.id); await mutate({ action:"toggleField", id:f.id, visible:e.target.checked, required:!!f.required }); setSaving(null); }} /><span />ظاهر</label><button className="row-menu">{saving === f.id ? "…" : "•••"}</button></div>)}</div></section><section className="panel preview-panel"><div className="preview-head"><div><span className="live-dot" />معاينة مباشرة</div><span>{selected.name}</span></div><div className="form-preview"><div className="preview-title"><span>＋</span><div><h3>نموذج {selected.name}</h3><p>المعاينة تتغير فورًا مع إعدادات الحقول.</p></div></div><div className="dynamic-grid">{previewFields.map((f) => <DynamicField key={f.id} field={f} value="" setValue={() => {}} data={data} values={{}} disabled />)}</div></div></section></div>;
}

function LeadsPage({ data, addLead, addCall, onAction }: { data: Setup; addLead: () => void; addCall: () => void; onAction: (lead: Lead, dialog: Dialog) => void }) {
  const newCount = data.leads.filter((lead) => lead.status === "new").length;
  const urgent = data.leads.filter((lead) => lead.priority === "urgent").length;
  return <div className="content-stack lead-board">
    <section className="metrics"><Metric label="إجمالي الـLeads" value={data.leads.length} hint="عملاء محتملون" tone="green" /><Metric label="جديدة" value={newCount} hint="لم تبدأ المتابعة" tone="blue" /><Metric label="أولوية عاجلة" value={urgent} hint="تحتاج تصرفًا سريعًا" tone="orange" /><Metric label="المكالمات" value={data.calls.length} hint="مسجلة في المرحلة" tone="purple" /></section>
    <section className="panel"><div className="panel-head"><div><h2>قائمة العملاء المحتملين</h2><p>رقم الهاتف فريد، وأي محاولة لتسجيله مرة أخرى ستظهر العميل الموجود.</p></div><div className="filters"><label className="search"><span>⌕</span><input placeholder="ابحث بالاسم أو الهاتف..." /></label><button className="secondary" onClick={addCall}>☎ مكالمة جديدة</button><button className="primary" onClick={addLead}>＋ Lead جديدة</button></div></div>
      {data.leads.length ? <div className="table-wrap"><table><thead><tr><th>العميل</th><th>الفرع</th><th>المصدر</th><th>الكورس</th><th>النتيجة</th><th>آخر مكالمة بواسطة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{data.leads.map((lead) => <tr key={lead.id}><td><div className="employee lead-person"><span>{initials(lead.fullName)}</span><div><strong>{lead.fullName}</strong><small>{lead.primaryPhone}</small></div></div></td><td>{lead.branchName || "—"}</td><td><span className="source-chip">{lead.source}</span></td><td>{lead.interest || "—"}</td><td><CallResult value={lead.lastCallResult || "no_answer"} /></td><td>{lead.lastCallBy || lead.assignedEmployee || "—"}</td><td><LeadStatus value={lead.status} /></td><td><div className="lead-actions"><button className="followup" onClick={() => onAction(lead, "scheduleFollowup")} title="جدولة متابعة">◷</button><button className="complete" onClick={() => onAction(lead, "leadDetails")} title="استكمال بيانات العميل">✎</button><button className="result" onClick={() => onAction(lead, "callResult")} title="تسجيل نتيجة المكالمة">?</button><button className="history" onClick={() => onAction(lead, "leadHistory")} title="سجل المكالمات">☷</button></div></td></tr>)}</tbody></table></div> : <div className="empty"><span>◇</span><h3>لا توجد Leads حتى الآن</h3><p>سجل أول عميل محتمل وحدد مصدره والموظف المسؤول.</p><button className="primary" onClick={addLead}>＋ تسجيل Lead جديدة</button></div>}
      <div className="table-footer"><span>إجمالي {data.leads.length} عميل محتمل</span><span className="duplicate-guard">✓ منع تكرار الهاتف مفعّل</span></div>
    </section>
  </div>;
}

function CallsPage({ data, add, mode }: { data: Setup; add: () => void; mode: "incoming" | "all" }) {
  const calls = mode === "incoming" ? data.calls.filter((call) => call.direction === "incoming") : data.calls;
  const answered = calls.filter((call) => call.result === "answered").length;
  const linked = calls.filter((call) => call.leadId).length;
  const heading = mode === "incoming" ? "Inbound Calls" : "Call Center Calls";
  return <div className="content-stack"><section className="metrics"><Metric label="إجمالي المكالمات" value={calls.length} hint={mode === "incoming" ? "مكالمات واردة" : "كل المكالمات المسجلة"} tone="green" /><Metric label="تم الرد" value={answered} hint="مكالمات مكتملة" tone="blue" /><Metric label="مرتبطة بعميل" value={linked} hint="تم التعرف على الرقم" tone="orange" /><Metric label="أرقام جديدة" value={calls.length - linked} hint="غير مرتبطة بـLead" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>{heading}</h2><p>يتم البحث عن رقم الهاتف وربطه تلقائيًا بعميل موجود.</p></div><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>{calls.length ? <div className="table-wrap"><table><thead><tr><th>العميل / الرقم</th><th>الفرع</th><th>نوع المكالمة</th><th>النتيجة</th><th>الموظف المسؤول</th><th>التوقيت</th><th>الملاحظات</th></tr></thead><tbody>{calls.map((call) => <tr key={call.id}><td><div className="call-identity"><strong>{call.leadName || "رقم غير مسجل"}</strong><small>{call.phone}</small></div></td><td>{call.branchName || "—"}</td><td><span className={`direction ${call.direction}`}>{call.direction === "incoming" ? "↙ واردة" : "↗ صادرة"}</span></td><td><CallResult value={call.result} /></td><td>{call.assignedEmployee || "غير معيّن"}</td><td>{formatDate(call.callAt)}</td><td className="notes-cell">{call.notes || "—"}</td></tr>)}</tbody></table></div> : <div className="empty"><span>☎</span><h3>{mode === "incoming" ? "لا توجد مكالمات واردة" : "لا توجد مكالمات مسجلة"}</h3><p>سجل مكالمة جديدة، وسيتم ربطها بالـLead تلقائيًا.</p><button className="primary" onClick={add}>＋ تسجيل مكالمة</button></div>}</section></div>;
}

function FollowupsPage({ data, mode, onAction }: { data: Setup; mode: "all" | "due"; onAction: (followup: Followup, dialog: Dialog) => void }) {
  const now = Date.now();
  const todayEnd = new Date(); todayEnd.setHours(23,59,59,999);
  const pending = data.followups.filter((followup) => followup.status === "pending");
  const rows = mode === "due" ? pending.filter((followup) => new Date(followup.scheduledAt).getTime() <= todayEnd.getTime()) : data.followups;
  const overdue = pending.filter((followup) => new Date(followup.scheduledAt).getTime() < now).length;
  const today = pending.filter((followup) => { const time=new Date(followup.scheduledAt); const date=new Date(); return time.toDateString()===date.toDateString(); }).length;
  const completed = data.followups.filter((followup) => followup.status === "completed").length;
  return <div className="content-stack followup-board"><section className="metrics"><Metric label="متابعات مفتوحة" value={pending.length} hint="في انتظار الإجراء" tone="green" /><Metric label="مستحقة اليوم" value={today} hint="ضمن خطة اليوم" tone="blue" /><Metric label="متأخرة" value={overdue} hint="تحتاج إجراءً سريعًا" tone="orange" /><Metric label="مكتملة" value={completed} hint="تم حفظ نتيجتها" tone="purple" /></section><section className="panel"><div className="panel-head"><div><h2>{mode === "due" ? "المتابعات الواردة والمستحقة" : "جدول متابعات الـLeads"}</h2><p>{mode === "due" ? "المواعيد المتأخرة والمستحقة حتى نهاية اليوم." : "كل المتابعات القادمة والمكتملة مرتبة حسب الموعد."}</p></div><span className="followup-live"><i /> تحديث تلقائي حسب الوقت</span></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>العميل</th><th>الموعد</th><th>التوقيت</th><th>الوسيلة</th><th>المسؤول</th><th>الفرع</th><th>الأولوية</th><th>الملاحظات / النتيجة</th><th>الإجراء</th></tr></thead><tbody>{rows.map((followup)=><tr key={followup.id} className={followupTiming(followup)==="overdue"?"overdue-row":""}><td><div className="call-identity"><strong>{followup.leadName}</strong><small>{followup.leadPhone}</small></div></td><td>{formatDate(followup.scheduledAt)}</td><td><FollowupTiming followup={followup}/></td><td><span className="channel-chip">{followupChannel(followup.channel)}</span></td><td>{followup.assignedEmployee||"غير معيّن"}</td><td>{followup.branchName||"—"}</td><td><Priority value={followup.priority}/></td><td className="notes-cell">{followup.status==="completed"?followup.outcome:followup.notes}</td><td>{followup.status==="pending"?<div className="followup-actions"><button className="done" onClick={()=>onAction(followup,"completeFollowup")}>✓ إنهاء</button><button onClick={()=>onAction(followup,"rescheduleFollowup")}>◷ تأجيل</button></div>:<span className="tag support">مكتملة</span>}</td></tr>)}</tbody></table></div>:<div className="empty"><span>◷</span><h3>{mode==="due"?"لا توجد متابعات مستحقة":"لا توجد متابعات حتى الآن"}</h3><p>{mode==="due"?"كل المواعيد الحالية تمت متابعتها.":"يمكن جدولة متابعة من زر الساعة داخل قائمة الـLeads."}</p></div>}</section></div>;
}

function followupTiming(followup: Followup) { if(followup.status==="completed") return "completed"; const due=new Date(followup.scheduledAt).getTime(); const now=Date.now(); if(due<now) return "overdue"; if(due-now<24*60*60*1000) return "today"; return "upcoming"; }
function FollowupTiming({followup}:{followup:Followup}) { const value=followupTiming(followup); const labels:Record<string,string>={completed:"تمت",overdue:"متأخرة",today:"خلال 24 ساعة",upcoming:"قادمة"}; return <span className={`followup-timing ${value}`}><i/>{labels[value]}</span>; }
function followupChannel(value:string) { return ({call:"مكالمة",whatsapp:"واتساب",message:"رسالة",visit:"زيارة",online_meeting:"اجتماع أونلاين"} as Record<string,string>)[value]||value; }

function Priority({ value }: { value: string }) { const labels: Record<string,string> = { normal:"عادية", high:"مرتفعة", urgent:"عاجلة" }; return <span className={`priority ${value}`}>{labels[value] || value}</span>; }
function LeadStatus({ value }: { value: string }) { const labels: Record<string,string> = { new:"جديدة", contacted:"تم التواصل", qualified:"مؤهلة", unqualified:"غير مؤهلة", followup:"متابعة" }; return <span className={`lead-status ${value}`}><i />{labels[value] || value}</span>; }
function CallResult({ value }: { value: string }) { const labels: Record<string,string> = { answered:"تم الرد", no_answer:"لم يرد", interested:"مهتم", not_interested:"غير مهتم", busy:"مشغول", wrong_number:"رقم خاطئ", callback:"معاودة الاتصال" }; return <span className={`call-result ${value}`}>{labels[value] || value}</span>; }
function formatDate(value: string) { try { return new Intl.DateTimeFormat("ar-EG", { dateStyle:"short", timeStyle:"short" }).format(new Date(value)); } catch { return value; } }

function LeadDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const [values,setValues]=useState<Record<string,unknown>>({}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.leadFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","primaryPhone","secondaryPhone","source","course","branchId","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,assignedEmployeeId:data.employees.find((employee)=>employee.status==="active")?.id,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل العميل");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◇</span><div><h2>تسجيل Lead جديدة</h2><p>بيانات العميل ومصدره والموظف المسؤول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error duplicate-error">{error}</p>}<div className="employee-form-note"><span>✓</span><p>سيتم تنظيف رقم الهاتف ومراجعته لمنع تسجيل نفس العميل مرتين.</p></div><div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التحقق والحفظ...":"تسجيل العميل"}</button></div></form></div>;
}

function CallDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const now=new Date(); now.setMinutes(now.getMinutes()-now.getTimezoneOffset()); const [values,setValues]=useState<Record<string,unknown>>({direction:"صادرة",result:"تم الرد",callAt:now.toISOString().slice(0,16)}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.callFields.filter((f)=>f.visible);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["phone","direction","result","assignedEmployeeId","branchId","callAt","notes"]);const customData=Object.fromEntries(Object.entries(values).filter(([key])=>!standard.has(key)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر تسجيل المكالمة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog compact-sales" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">☎</span><div><h2>تسجيل مكالمة جديدة</h2><p>لو الرقم مسجل سيتم ربط المكالمة بالعميل تلقائيًا.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields">{fields.map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ التسجيل...":"حفظ المكالمة"}</button></div></form></div>;
}

function FollowupDialog({ lead, data, onClose, onSubmit }: { lead: Lead; data: Setup; onClose: () => void; onSubmit: (p: Record<string,unknown>) => Promise<void> }) {
  const next=new Date(Date.now()+60*60*1000); next.setMinutes(next.getMinutes()-next.getTimezoneOffset());
  const [values,setValues]=useState<Record<string,unknown>>({scheduledAt:next.toISOString().slice(0,16),assignedEmployeeId:lead.assignedEmployeeId||data.employees.find((employee)=>employee.status==="active")?.id,channel:"مكالمة",priority:"عادية"}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر جدولة المتابعة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog compact-sales" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◷</span><div><h2>جدولة متابعة جديدة</h2><p>{lead.fullName} · {lead.primaryPhone}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>النموذج ديناميكي، والموعد سيظهر تلقائيًا في قائمة المسؤول والمتابعات المستحقة.</p></div><div className="dynamic-grid dialog-fields">{data.followupFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الجدولة...":"حفظ موعد المتابعة"}</button></div></form></div>;
}

function CompleteFollowupDialog({followup,onClose,onSubmit}:{followup:Followup;onClose:()=>void;onSubmit:(outcome:string)=>Promise<void>}) { const [outcome,setOutcome]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(outcome)}catch(err){setError(err instanceof Error?err.message:"تعذر إنهاء المتابعة");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">✓</span><div><h2>إنهاء المتابعة</h2><p>{followup.leadName} · {followupChannel(followup.channel)}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields"><label className="full"><span>نتيجة المتابعة *</span><textarea required value={outcome} onChange={(e)=>setOutcome(e.target.value)} placeholder="ماذا حدث؟ وما هي الخطوة التالية؟"/></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"إنهاء وحفظ النتيجة"}</button></div></form></div>; }

function RescheduleDialog({followup,onClose,onSubmit}:{followup:Followup;onClose:()=>void;onSubmit:(scheduledAt:string)=>Promise<void>}) { const initial=new Date(followup.scheduledAt); initial.setMinutes(initial.getMinutes()-initial.getTimezoneOffset()); const [scheduledAt,setScheduledAt]=useState(initial.toISOString().slice(0,16)); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(scheduledAt)}catch(err){setError(err instanceof Error?err.message:"تعذر تعديل الموعد");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◷</span><div><h2>تعديل موعد المتابعة</h2><p>{followup.leadName}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="dynamic-grid dialog-fields"><label className="full"><span>الموعد الجديد *</span><input type="datetime-local" required value={scheduledAt} onChange={(e)=>setScheduledAt(e.target.value)}/></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ الموعد الجديد"}</button></div></form></div>; }

function leadCustomData(lead: Lead) { try { return JSON.parse(lead.customData || "{}") as Record<string, unknown>; } catch { return {}; } }

function LeadDetailsDialog({ lead, fields, data, onClose, onSubmit }: { lead: Lead; fields: Field[]; data: Setup; onClose: () => void; onSubmit: (details: Record<string,unknown>) => Promise<void> }) {
  const [values,setValues]=useState<Record<string,unknown>>({ ...leadCustomData(lead), course:lead.interest, source:lead.source }); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ البيانات");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog sales-dialog details-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">✎</span><div><h2>استكمال بيانات العميل</h2><p>بيانات البيع والتصنيف الخاصة بـ {lead.fullName}</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="lead-fixed-fields"><label><span>الاسم</span><input value={lead.fullName} disabled /></label><label><span>رقم الموبايل</span><input value={lead.primaryPhone} disabled /></label><label><span>رقم الموبايل 2</span><input value={lead.secondaryPhone || "—"} disabled /></label></div><div className="dynamic-grid dialog-fields">{fields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إغلاق</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ باقي البيانات"}</button></div></form></div>;
}

function LeadCallResultDialog({ lead, onClose, onSubmit }: { lead: Lead; onClose: () => void; onSubmit: (payload: Record<string,unknown>) => Promise<void> }) {
  const [result,setResult]=useState("No Answer"); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit({result,notes})}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ النتيجة");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact call-result-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">☎</span><div><h2>نتيجة المكالمة</h2><p>تسجيل نتيجة اتصال فريق المبيعات</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="lead-fixed-fields stacked"><label><span>الاسم</span><input value={lead.fullName} disabled /></label><label><span>رقم الموبايل</span><input value={lead.primaryPhone} disabled /></label><label><span>رقم الموبايل 2</span><input value={lead.secondaryPhone || "—"} disabled /></label></div><div className="dynamic-grid dialog-fields result-fields"><label className="full"><span>نتيجة المكالمة *</span><select value={result} onChange={(e)=>setResult(e.target.value)} required><option>No Answer</option><option>Answered</option><option>Interested</option><option>Not Interested</option><option>Busy</option><option>Wrong Number</option><option>Call Back</option></select></label><label className="full"><span>ملاحظات</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="اكتب ملخص المكالمة" /></label></div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إغلاق</button><button className="primary warning" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ النتيجة"}</button></div></form></div>;
}

function LeadHistoryDialog({ lead, calls, onClose }: { lead: Lead; calls: CallRecord[]; onClose: () => void }) {
  const details=leadCustomData(lead); const detailRows=[["الاسم",lead.fullName],["موبايل 1",lead.primaryPhone],["موبايل 2",lead.secondaryPhone||"—"],["النوع",String(details.gender||"—")],["العمر",String(details.age||"—")],["الموقع",String(details.location||"—")],["الفرع",lead.branchName||"—"],["الكورس",lead.interest||"—"],["الشريحة",String(details.segment||"—")],["الوظيفة",String(details.job||"—")],["العرض",String(details.offer||"—")]];
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="dialog history-dialog"><div className="dialog-head"><div><span className="dialog-icon">◉</span><div><h2>سجل العميل [{lead.primaryPhone}]</h2><p>البيانات الكاملة وكل المكالمات المسجلة</p></div></div><button onClick={onClose}>×</button></div><div className="history-summary">{detailRows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="history-section"><h3>سجل المكالمات</h3>{calls.length?<div className="table-wrap"><table><thead><tr><th>النتيجة</th><th>المرحلة</th><th>وقت الإجراء</th><th>الملاحظات</th><th>الموظف</th></tr></thead><tbody>{calls.map((call)=><tr key={call.id}><td><CallResult value={call.result}/></td><td>Lead</td><td>{formatDate(call.callAt)}</td><td className="notes-cell">{call.notes||"—"}</td><td>{call.assignedEmployee||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-history">لا توجد مكالمات مسجلة لهذا العميل.</div>}</div><div className="dialog-foot"><button className="secondary" onClick={onClose}>إغلاق</button></div></section></div>;
}

function Metric({ label, value, hint, tone }: { label: string; value: number; hint: string; tone: string }) { return <article className="metric"><span className={`metric-icon ${tone}`}>◆</span><div><small>{label}</small><strong>{String(value).padStart(2,"0")}</strong><p>{hint}</p></div></article>; }
function Status({ status }: { status: Employee["status"] }) { const map = { active:"نشط", invited:"دعوة معلقة", disabled:"موقوف" }; return <span className={`status ${status}`}><i />{map[status]}</span>; }
function initials(name: string) { return name.split(" ").slice(0,2).map((part) => part[0]).join(""); }
function parseOptions(field: Field) { try { return JSON.parse(field.optionsJson || "[]") as string[]; } catch { return []; } }

function EmployeeDialog({ data, onClose, onSubmit }: { data: Setup; onClose: () => void; onSubmit: (p: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState<Record<string, unknown>>({ startDate: new Date().toISOString().slice(0,10) }); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const fields=data.fields.filter((f)=>f.visible);
  async function submit(e: FormEvent){e.preventDefault();setBusy(true);setError("");try{const standard=new Set(["fullName","email","phone","departmentId","jobTitleId","roleId","branchId","status"]);const customData=Object.fromEntries(Object.entries(values).filter(([k])=>!standard.has(k)));await onSubmit({...values,customData});}catch(err){setError(err instanceof Error?err.message:"تعذر الحفظ");setBusy(false)}}
  return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog employee-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">＋</span><div><h2>إضافة موظف جديد</h2><p>بيانات الملف الوظيفي وحساب الدخول.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>▤</span><p>هذا النموذج ديناميكي. يمكنك إخفاء أي حقل أو إضافة حقول جديدة من «مصمم النماذج».</p></div><div className="dynamic-grid dialog-fields">{fields.map((f)=><DynamicField key={f.id} field={f} value={values[f.fieldKey]} setValue={(v)=>setValues((current)=>({...current,[f.fieldKey]:v}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":"إنشاء ملف الموظف"}</button></div></form></div>;
}

function DynamicField({ field, value, setValue, data, values, disabled=false }: { field: Field; value: unknown; setValue:(v:unknown)=>void; data:Setup; values:Record<string,unknown>; disabled?:boolean }) {
  let options:{id:string|number;name:string}[]=parseOptions(field).map((name)=>({id:name,name}));
  if(field.fieldKey==="departmentId") options=data.departments.map((d)=>({id:d.id,name:d.name}));
  if(field.fieldKey==="jobTitleId") options=data.jobTitles.filter((j)=>!values.departmentId||j.departmentId===Number(values.departmentId)).map((j)=>({id:j.id,name:j.name}));
  if(field.fieldKey==="roleId") options=data.roles.map((r)=>({id:r.id,name:r.name}));
  if(field.fieldKey==="assignedEmployeeId") options=data.employees.filter((employee)=>employee.status==="active").map((employee)=>({id:employee.id,name:employee.fullName}));
  if(field.fieldKey==="branchId") options=data.branches.filter((branch)=>branch.isActive||Number(value)===branch.id).map((branch)=>({id:branch.id,name:branch.name}));
  if(field.fieldKey==="interest") options=data.tracks.filter((track)=>track.isActive||String(value)===track.title).map((track)=>({id:track.title,name:track.title}));
  const common={disabled,required:!!field.required};
  if(field.type==="textarea") return <label className="full"><span>{field.label}{field.required?" *":""}</span><textarea value={String(value??"")} placeholder={field.placeholder} onChange={(e)=>setValue(e.target.value)} disabled={disabled} required={!!field.required}/></label>;
  if(field.type==="checkbox") { const selected=Array.isArray(value)?value as string[]:[]; return <fieldset className="full document-field"><legend>{field.label}</legend><div>{options.map((o)=><label key={o.id}><input type="checkbox" checked={selected.includes(String(o.id))} disabled={disabled} onChange={(e)=>setValue(e.target.checked?[...selected,String(o.id)]:selected.filter((x)=>x!==String(o.id)))} /><span>✓</span>{o.name}</label>)}</div></fieldset>; }
  return <label className={field.width==="full"?"full":""}><span>{field.label}{field.required?" *":""}</span>{field.type==="select"?<select value={String(value??"")} onChange={(e)=>setValue(e.target.value)} {...common}><option value="">{field.placeholder}</option>{options.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input value={String(value??"")} onChange={(e)=>setValue(e.target.value)} placeholder={field.placeholder} type={field.type} {...common}/>}</label>;
}
function BaseDialog({ title, subtitle, icon, onClose, onSubmit, children, busyText="جارٍ الحفظ...", submitText="حفظ" }: { title:string;subtitle:string;icon:string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode;busyText?:string;submitText?:string }) { const [busy,setBusy]=useState(false); return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog compact" onSubmit={(e)=>{setBusy(true);onSubmit(e)}}><div className="dialog-head"><div><span className="dialog-icon">{icon}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div><button type="button" onClick={onClose}>×</button></div><div className="dynamic-grid dialog-fields">{children}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?busyText:submitText}</button></div></form></div>; }

function DepartmentDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة قسم" subtitle="سيظهر مباشرة داخل نموذج الموظف" icon="≡" onClose={onClose} submitText="إضافة القسم" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),parentId:f.get("parentId"),color:f.get("color"),supportEnabled:f.get("supportEnabled")==="on"})}}><label className="full"><span>اسم القسم *</span><input name="name" required placeholder="مثال: التسويق" /></label><label><span>القسم الرئيسي</span><select name="parentId"><option value="">بدون قسم رئيسي</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span>لون القسم</span><input name="color" type="color" defaultValue="#2f6b5f" /></label><label className="inline-check full"><input type="checkbox" name="supportEnabled" /> تفعيل خيارات الدعم لهذا القسم</label></BaseDialog>; }
function ClassroomDialog({data,room,onClose,onSubmit}:{data:Setup;room:Classroom|null;onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { const base=room?{name:room.name,branchId:room.branchId,capacity:room.capacity,isActive:room.isActive?"نشط":"غير نشط"}:{isActive:"نشط"};let extras:Record<string,unknown>={};try{extras=room?JSON.parse(room.customData||"{}"):{};}catch{extras={}}const [values,setValues]=useState<Record<string,unknown>>({...extras,...base});const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر حفظ القاعة");setBusy(false)}}return <div className="overlay" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><form className="dialog class-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">▦</span><div><h2>{room?"تعديل Class":"إضافة Class جديدة"}</h2><p>حدد الفرع واسم القاعة وسعتها.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>هذا النموذج ديناميكي ويمكن التحكم في حقوله من Admin Settings.</p></div><div className="dynamic-grid dialog-fields">{data.classroomFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":room?"حفظ التعديلات":"إضافة القاعة"}</button></div></form></div>;}
function TrackDialog({data,track,onClose,onSubmit}:{data:Setup;track:Track|null;onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { const base=track?{title:track.title,isActive:track.isActive?"نشط":"غير نشط"}:{isActive:"نشط"};let extras:Record<string,unknown>={};try{extras=track?JSON.parse(track.customData||"{}"):{};}catch{extras={}}const [values,setValues]=useState<Record<string,unknown>>({...extras,...base});const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر حفظ الـTrack");setBusy(false)}}return <div className="overlay" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><form className="dialog track-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">◇</span><div><h2>{track?"تعديل Track":"إضافة Track جديدة"}</h2><p>اسم المسار وحالته داخل النظام.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>النموذج ديناميكي، والـTracks النشطة تظهر فورًا داخل نموذج الـLead.</p></div><div className="dynamic-grid dialog-fields">{data.trackFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":track?"حفظ التعديلات":"إضافة الـTrack"}</button></div></form></div>;}
function BranchDialog({data,branch,onClose,onSubmit}:{data:Setup;branch:Branch|null;onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { const [values,setValues]=useState<Record<string,unknown>>(branch?{name:branch.name,address:branch.address,primaryPhone:branch.primaryPhone,secondaryPhone:branch.secondaryPhone,email:branch.email,socialUrl:branch.socialUrl,isActive:branch.isActive?"نشط":"غير نشط"}:{isActive:"نشط"}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onSubmit(values)}catch(err){setError(err instanceof Error?err.message:"تعذر حفظ الفرع");setBusy(false)}} return <div className="overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="dialog employee-dialog" onSubmit={submit}><div className="dialog-head"><div><span className="dialog-icon">⌂</span><div><h2>{branch?"تعديل بيانات الفرع":"إضافة فرع جديد"}</h2><p>مصدر موحد للفروع في كل نماذج النظام.</p></div></div><button type="button" onClick={onClose}>×</button></div>{error&&<p className="form-error">{error}</p>}<div className="employee-form-note"><span>↻</span><p>النموذج ديناميكي، وتحديث الفرع ينعكس فورًا على الموظفين والـLeads والمكالمات المرتبطة.</p></div><div className="dynamic-grid dialog-fields">{data.branchFields.filter((field)=>field.visible).map((field)=><DynamicField key={field.id} field={field} value={values[field.fieldKey]} setValue={(value)=>setValues((current)=>({...current,[field.fieldKey]:value}))} data={data} values={values}/>)}</div><div className="dialog-foot"><button className="secondary" type="button" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جارٍ الحفظ...":branch?"حفظ التعديلات":"إضافة الفرع"}</button></div></form></div>; }
function JobDialog({departments,onClose,onSubmit}:{departments:Department[];onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="إضافة دور وظيفي" subtitle="اختر القسم الذي تتبعه الوظيفة" icon="◆" onClose={onClose} submitText="إضافة الوظيفة" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({name:f.get("name"),departmentId:f.get("departmentId")})}}><label className="full"><span>اسم الوظيفة *</span><input name="name" required placeholder="مثال: مسؤول مبيعات" /></label><label className="full"><span>القسم *</span><select name="departmentId" required><option value="">اختر القسم</option>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></BaseDialog>; }
function FieldDialog({onClose,onSubmit}:{onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}) { return <BaseDialog title="حقل جديد" subtitle="سيظهر داخل نموذج الإدخال المحدد" icon="▤" onClose={onClose} submitText="إضافة الحقل" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSubmit({formKey:f.get("formKey"),label:f.get("label"),type:f.get("type"),placeholder:f.get("placeholder"),width:f.get("width"),required:f.get("required")==="on"})}}><label className="full"><span>النموذج *</span><select name="formKey" required><option value="employee">الموظف</option><option value="branch">الفرع</option><option value="classroom">القاعة</option><option value="track">الـTrack</option><option value="lead">Lead جديدة</option><option value="call">المكالمة</option><option value="lead_details">استكمال بيانات العميل</option><option value="followup">المتابعة</option></select></label><label className="full"><span>اسم الحقل *</span><input name="label" required /></label><label><span>النوع</span><select name="type"><option value="text">نص</option><option value="number">رقم</option><option value="date">تاريخ</option><option value="textarea">نص طويل</option></select></label><label><span>العرض</span><select name="width"><option value="half">نصف صف</option><option value="full">صف كامل</option></select></label><label className="full"><span>النص الإرشادي</span><input name="placeholder" /></label><label className="inline-check full"><input type="checkbox" name="required" /> حقل إلزامي</label></BaseDialog>; }
