import { env } from "cloudflare:workers";
import { ensurePhaseTwo, normalizePhone } from "@/db/phase-two";
import * as XLSX from "xlsx";

export const dynamic = "force-dynamic";

type Row=Record<string,unknown>;
const tokenFrom=(request:Request)=>request.headers.get("cookie")?.split(";").map(v=>v.trim()).find(v=>v.startsWith("masar_session="))?.slice(14)||"";
const value=(row:Row,...names:string[])=>{for(const name of names)if(row[name]!==undefined&&row[name]!==null)return String(row[name]).trim();return ""};
const dateValue=(input:unknown)=>{const raw=String(input??"").trim(),serial=Number(raw);if(raw&&Number.isFinite(serial)&&serial>=20_000&&serial<=80_000){const date=new Date(Date.UTC(1899,11,30)+Math.round(serial*86_400_000));return `${date.toISOString().slice(0,10)} ${date.toISOString().slice(11,19)}`}const match=raw.match(/\d{4}-\d{2}-\d{2}(?:[ T]\d{2}:\d{2}(?::\d{2})?)?/);return match?.[0]||raw};
const key=(...parts:unknown[])=>parts.map(part=>String(part||"").trim().toLowerCase()).join("|");
const normalizedLabel=(input:unknown)=>String(input||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\u00a0/g," ").trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim();
const labelTokens=(input:unknown)=>normalizedLabel(input).split(" ").filter(Boolean);
const excelTime=(input:unknown)=>{const numeric=Number(input);if(Number.isFinite(numeric)&&numeric>=0&&numeric<1){const minutes=Math.round(numeric*24*60);return `${String(Math.floor(minutes/60)%24).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`}const match=String(input||"").match(/(\d{1,2}):(\d{2})/);return match?`${match[1].padStart(2,"0")}:${match[2]}`:""};
const importDate=(input:unknown)=>{const raw=String(input||"").trim(),direct=dateValue(raw);if(/^\d{4}-\d{2}-\d{2}/.test(direct))return direct.slice(0,10);const match=raw.match(/(?:\w+\s+)?(\d{1,2})\s+([A-Za-z]{3})/);if(!match)return "";const months=["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"],month=months.indexOf(match[2].toLowerCase());return month<0?"":`${new Date().getFullYear()}-${String(month+1).padStart(2,"0")}-${match[1].padStart(2,"0")}`};
const history=(raw:string)=>raw.split("@@").map(part=>({at:part.match(/Datetime=>([^,]+)/)?.[1]?.trim()||"",notes:part.match(/Note=>(.*?)(?:,Employee=>|$)/)?.[1]?.trim()||"",employee:part.match(/Employee=>(.*)$/)?.[1]?.trim()||""})).filter(item=>item.at||item.notes);
const callResult=(input:unknown)=>{const result=String(input||"").trim().toLowerCase();if(result==="no answer"||result==="not answered")return "No Answer";if(result==="busy")return "Busy";if(result==="wrong number")return "Wrong Number";if(result==="call back"||result==="callback")return "Call Back";if(result==="not interested")return "Not Interested";if(result==="interested")return "Interested";return "Answered"};
const callResultFromNote=(note:unknown,fallback:unknown="")=>{const explicit=String(fallback||"").trim();if(explicit)return callResult(explicit);const text=String(note||"").trim().toLowerCase();if(!text)return "Answered";if(/no\s*answer|not\s*answered|voice|فويس|مردش|مردتش|مش\s*بيرد|لم\s*يرد/.test(text))return "No Answer";if(/busy|مشغول/.test(text))return "Busy";if(/wrong\s*number|رقم\s*غلط|غلط/.test(text))return "Wrong Number";if(/call\s*back|callback|تابع|متابعه|متابعة/.test(text))return "Call Back";if(/not\s*interested|مش\s*مهتم|لغي|رفض/.test(text))return "Not Interested";return "Answered"};
const importedPaymentType=(offer:string)=>{const label=offer.toLowerCase();if(/material|\bbook\b/.test(label))return "Books";if(/make up|makeup/.test(label))return "Make Up";if(/delivery|shipping|courier/.test(label))return "Delivery";if(label.includes("certificate"))return "Certificate";if(label.includes("placement"))return "Placement Test";if(/\bexam\b|\btest\b/.test(label))return "Test";if(/retention|\brete?n?\b/.test(label))return "Retention";if(label.includes("renewal"))return "Renewal";if(label.includes("new comer"))return "New Comers";if(label.includes("private"))return "Private";return "Other"};

export async function POST(request:Request){
  try{
    await ensurePhaseTwo();const db=env.DB,token=tokenFrom(request),session=token?await db.prepare("SELECT e.id,e.job_title_id AS jobTitleId FROM employee_sessions s JOIN employees e ON e.id=s.employee_id WHERE s.token=? AND s.expires_at>? LIMIT 1").bind(token,new Date().toISOString()).first<{id:number;jobTitleId:number}>():null;
    if(!session)return Response.json({error:"يجب تسجيل الدخول أولًا"},{status:401});
    const form=await request.formData(),kind=String(form.get("kind")||""),file=form.get("file");if(!(file instanceof File))return Response.json({error:"اختر ملف Excel"},{status:400});
    const pageByKind:Record<string,string>={students:"studentsList",payments:"payments",absence:"operationsAbsenceReports",leads:"leads",callCenter:"callCenterCalls",received:"inboundCalls",groupsData:"groups",groupStudents:"groups"},page=pageByKind[kind];if(!page)return Response.json({error:"نوع الملف غير مدعوم"},{status:400});
    const permission=await db.prepare("SELECT can_add AS canAdd FROM job_title_permissions WHERE job_title_id=? AND page_key=?").bind(session.jobTitleId,page).first<{canAdd:number}>();if(permission&&!permission.canAdd)return Response.json({error:"لا توجد صلاحية لرفع بيانات هذه الصفحة"},{status:403});
    const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json<Row>(sheet,{defval:""});if(!rows.length)return Response.json({error:"الملف لا يحتوي على بيانات"},{status:400});
    const [branches,employees,tracks,levels,groups,offers]=await Promise.all([db.prepare("SELECT id,name FROM branches").all<{id:number;name:string}>(),db.prepare("SELECT id,full_name AS name FROM employees").all<{id:number;name:string}>(),db.prepare("SELECT id,title FROM tracks").all<{id:number;title:string}>(),db.prepare("SELECT id,title FROM settings_entities WHERE kind='level'").all<{id:number;title:string}>(),db.prepare("SELECT id,title,custom_data AS customData FROM settings_entities WHERE kind='group'").all<{id:number;title:string;customData:string}>(),db.prepare("SELECT id,title,custom_data AS customData FROM settings_entities WHERE kind='offer'").all<{id:number;title:string;customData:string}>()]);
    const findId=(list:Array<{id:number;name?:string;title?:string}>,label:string)=>{const target=normalizedLabel(label);if(!target)return null;const exact=list.filter(item=>normalizedLabel(item.name||item.title||"")===target);if(exact.length===1)return exact[0].id;const tokens=labelTokens(label),matches=list.filter(item=>{const candidate=labelTokens(item.name||item.title||"");return tokens.length>0&&tokens.every(token=>candidate.includes(token))});return matches.length===1?matches[0].id:null};
    if(kind==="groupsData"){
      const [batches,rounds,studyTypes,timeSlots]=await Promise.all([
        db.prepare("SELECT id,title,custom_data AS customData FROM settings_entities WHERE kind='education_batch'").all<{id:number;title:string;customData:string}>(),
        db.prepare("SELECT id,title FROM settings_entities WHERE kind='round'").all<{id:number;title:string}>(),
        db.prepare("SELECT id,title FROM settings_entities WHERE kind='study_type'").all<{id:number;title:string}>(),
        db.prepare("SELECT id,track_id AS trackId,start_time AS startTime,end_time AS endTime FROM time_slots").all<{id:number;trackId:number;startTime:string;endTime:string}>(),
      ]),batchByTitle=new Map(batches.results.map(item=>[normalizedLabel(item.title),item]));
      const employeeMatch=(name:string,currentId?:number)=>{const search=normalizedLabel(name),searchTokens=labelTokens(name);if(!search||["no show","none","na"].includes(search))return null;const matches=employees.results.filter(item=>{const candidate=normalizedLabel(item.name),candidateTokens=labelTokens(item.name);return candidate===search||candidate.startsWith(`${search} `)||search.startsWith(`${candidate} `)||(searchTokens.length>=2&&searchTokens.every(token=>candidateTokens.includes(token)))});return matches.length===1?matches[0].id:matches.find(item=>item.id===currentId)?.id||null};
      let created=0,updated=0,invalid=0;const statements=[] as ReturnType<typeof db.prepare>[];
      for(const row of rows){
        const groupId=Number(value(row,"Id","Group Id","Group ID")),batchTitle=value(row,"Batch"),levelTitle=value(row,"Level"),german=batchTitle.toLowerCase().includes("german"),track=tracks.results.find(item=>normalizedLabel(item.title).includes(german?"german":"english")),levelId=findId(levels.results,levelTitle),branchId=branches.results.find(item=>normalizedLabel(item.name)===normalizedLabel(value(row,"Location")))?.id;
        if(!groupId||!batchTitle||!track||!levelId||!branchId){invalid++;continue}
        let batch=batchByTitle.get(normalizedLabel(batchTitle));if(!batch){const batchData={trackId:track.id,batchStatus:"Current Batch",importSource:file.name};const result=await db.prepare("INSERT INTO settings_entities (kind,title,is_active,custom_data) VALUES ('education_batch',?,1,?)").bind(batchTitle,JSON.stringify(batchData)).run();batch={id:Number(result.meta.last_row_id),title:batchTitle,customData:JSON.stringify(batchData)};batchByTitle.set(normalizedLabel(batchTitle),batch)}
        const existing=groups.results.find(item=>item.id===groupId);let details:Record<string,unknown>={};if(existing)try{details=JSON.parse(existing.customData||"{}")}catch{}
        const startTime=excelTime(row.Time),friday=/^fri/i.test(value(row,"Start")),slots=timeSlots.results.filter(item=>item.trackId===track.id&&item.startTime.slice(0,5)===startTime).sort((a,b)=>friday?b.endTime.localeCompare(a.endTime):a.endTime.localeCompare(b.endTime)),round=rounds.results.find(item=>normalizedLabel(item.title).includes(german?"german":"english")&&normalizedLabel(item.title).includes("normal")),teacherName=value(row,"Teacher"),adminName=value(row,"Admin"),teacherId=employeeMatch(teacherName,Number(details.teacherId)),adminId=employeeMatch(adminName,Number(details.adminId)),next={...details,batchId:batch.id,trackId:track.id,levelId,branchId,studyTypeId:findId(studyTypes.results,"Group")||details.studyTypeId,roundId:round?.id||details.roundId,timeSlotId:slots[0]?.id||details.timeSlotId,startDate:importDate(row.Start)||details.startDate||"",sourceTeacherName:teacherName,sourceAdminName:adminName,legacyExternalId:groupId,legacyImportSource:file.name,legacyStudentCount:Number(row["No."]||0),sourceZoomFlag:Boolean(value(row,"Zoom")),groupStatus:String(details.groupStatus||"Running"),...(teacherId?{teacherId}:{}),...(adminId?{adminId}:{})};
        if(existing){statements.push(db.prepare("UPDATE settings_entities SET title=?,is_active=1,custom_data=? WHERE id=? AND kind='group'").bind(String(groupId),JSON.stringify(next),groupId));updated++}else{statements.push(db.prepare("INSERT INTO settings_entities (id,kind,title,is_active,custom_data) VALUES (?,'group',?,1,?)").bind(groupId,String(groupId),JSON.stringify(next)));created++}
      }
      for(let i=0;i<statements.length;i+=60)await db.batch(statements.slice(i,i+60));return Response.json({ok:true,created,updated,skipped:0,invalid,total:rows.length});
    }
    if(kind==="groupStudents"){
      const students=await db.prepare("SELECT id,full_name AS name,mobile,secondary_mobile AS secondary,custom_data AS customData FROM students").all<{id:number;name:string;mobile:string;secondary:string;customData:string}>(),members=await db.prepare("SELECT group_id AS groupId,student_reference AS studentId FROM group_members").all<{groupId:number;studentId:string}>(),byPhone=new Map<string,number[]>(),byName=new Map<string,number[]>();
      for(const student of students.results){for(const phone of [student.mobile,student.secondary]){const normalized=normalizePhone(phone);if(normalized)byPhone.set(normalized,[...(byPhone.get(normalized)||[]),student.id])}const name=normalizedLabel(student.name);byName.set(name,[...(byName.get(name)||[]),student.id])}
      const existing=new Set(members.results.map(item=>`${item.groupId}:${Number(item.studentId)}`));let created=0,skipped=0,invalid=0,studentsCreated=0;const statements=[] as ReturnType<typeof db.prepare>[];
      const groupById=new Map(groups.results.map((item)=>[item.id,item]));
      for(const row of rows){
        const groupId=Number(value(row,"Group Id","Group ID","Id"));if(!groupId||!groups.results.some(item=>item.id===groupId)){invalid++;continue}
        const phones=[normalizePhone(value(row,"Mobile 1")),normalizePhone(value(row,"Mobile 2"))].filter(Boolean),phoneMatches=[...new Set(phones.flatMap(phone=>byPhone.get(phone)||[]))],nameMatches=byName.get(normalizedLabel(value(row,"Name","Student Name")))||[];
        let studentId=phoneMatches.length===1?phoneMatches[0]:nameMatches.length===1?nameMatches[0]:phoneMatches.find(id=>nameMatches.includes(id));
        if(!studentId){
          const group=groupById.get(groupId);let groupDetails:Record<string,unknown>={};try{groupDetails=JSON.parse(group?.customData||"{}")}catch{}
          const name=value(row,"Name","Student Name");const primaryPhone=normalizePhone(value(row,"Mobile 1"));const secondaryPhone=normalizePhone(value(row,"Mobile 2"));const levelId=findId(levels.results,value(row,"Level"))||Number(groupDetails.levelId)||0;const trackId=Number(groupDetails.trackId)||0;const branchId=Number(groupDetails.branchId)||0;
          if(!name||(!primaryPhone&&!secondaryPhone)){invalid++;continue}
          const studentResult=await db.prepare("INSERT INTO students (full_name,mobile,secondary_mobile,email,level_id,track_id,branch_id,status,custom_data,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(name,primaryPhone,secondaryPhone,"",levelId,trackId,branchId,"active",JSON.stringify({importSource:file.name,legacyGroupId:groupId,gender:value(row,"Gender"),time:value(row,"Time"),location:value(row,"Location"),start:importDate(row.Start)||"",end:importDate(row.End)||"",level:value(row,"Level"),paymentHistory:value(row,"Payment History"),groupTitle:group?.title||""}),new Date().toISOString()).run();
          studentId=Number((studentResult.meta as {last_row_id?:number}).last_row_id||0);if(!studentId){invalid++;continue}
          studentsCreated++;
          byPhone.set(primaryPhone,[...(byPhone.get(primaryPhone)||[]),studentId]);if(secondaryPhone)byPhone.set(secondaryPhone,[...(byPhone.get(secondaryPhone)||[]),studentId]);const normalizedName=normalizedLabel(name);byName.set(normalizedName,[...(byName.get(normalizedName)||[]),studentId]);
        }
        const memberKey=`${groupId}:${studentId}`;if(existing.has(memberKey)){skipped++;continue}statements.push(db.prepare("INSERT INTO group_members (group_id,student_reference,added_by_employee_id,added_by_name,joined_at) VALUES (?,?,?,?,?)").bind(groupId,String(studentId),session.id,"Groups Excel Import",importDate(row.Start)||new Date().toISOString()));existing.add(memberKey);created++
      }
      for(let i=0;i<statements.length;i+=80)await db.batch(statements.slice(i,i+80));return Response.json({ok:true,created,updated:0,skipped,invalid,total:rows.length,studentsCreated});
    }
    if(kind==="students"){
      const existing=await db.prepare("SELECT mobile,secondary_mobile AS secondary FROM students").all<{mobile:string;secondary:string}>(),phones=new Set(existing.results.flatMap(item=>[normalizePhone(item.mobile),normalizePhone(item.secondary)]).filter(Boolean));let created=0,skipped=0,invalid=0;const statements=[] as ReturnType<typeof db.prepare>[];
      for(let index=0;index<rows.length;index++){const row=rows[index],phone=normalizePhone(value(row,"Mobile 1","Mobile","Phone")),secondaryPhone=normalizePhone(value(row,"Mobile 2","Secondary Mobile","Phone 2")),name=value(row,"Name","Student Name");if(!name||phone.length<8){invalid++;continue}if(phones.has(phone)){skipped++;continue}const levelId=findId(levels.results,value(row,"Level","Level Name"))||levels.results[0]?.id,trackId=findId(tracks.results,value(row,"Track","Track Name","Course")),branchId=findId(branches.results,value(row,"location","Location","Branch","Branch Name")),employeeId=findId(employees.results,value(row,"Employee","Empoyee","Employee Name","Created By")),employeeName=employees.results.find(item=>item.id===employeeId)?.name||value(row,"Employee","Empoyee","Employee Name","Created By");if(!levelId){invalid++;continue}const detail={importKey:key(file.name,value(row,"#ID","ID"),phone),legacyId:value(row,"#ID","ID"),gender:value(row,"Gender"),notes:value(row,"Notes"),referral:value(row,"Referal","Referral"),platform:value(row,"Platform"),area:value(row,"Area"),address:value(row,"Address"),job:value(row,"Job"),payments:value(row,"Payments"),history:history(value(row,"History")),importSource:file.name,sourceRow:index+2,createdById:employeeId||null,createdBy:employeeName||"System"};statements.push(db.prepare("INSERT INTO students (full_name,mobile,secondary_mobile,email,level_id,track_id,branch_id,status,custom_data,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(name,phone,secondaryPhone,value(row,"Student Email","Email")==="-"?"":value(row,"Student Email","Email"),levelId,trackId,branchId,"active",JSON.stringify(detail),dateValue(value(row,"Date","Created At","Created Date","DateTime"))||new Date().toISOString()));phones.add(phone);created++}
      for(let i=0;i<statements.length;i+=80)await db.batch(statements.slice(i,i+80));return Response.json({ok:true,created,skipped,invalid,total:rows.length});
    }
    if(kind==="payments"||kind==="absence"){
      const students=await db.prepare("SELECT id,full_name AS name,mobile,secondary_mobile AS secondary,custom_data AS customData FROM students").all<{id:number;name:string;mobile:string;secondary:string;customData:string}>(),studentByPhone=new Map<string,number>(),studentIdsByName=new Map<string,number[]>();for(const student of students.results){for(const phone of [student.mobile,student.secondary]){const normalized=normalizePhone(phone);if(normalized)studentByPhone.set(normalized,student.id)}const normalizedName=student.name.trim().toLowerCase();studentIdsByName.set(normalizedName,[...(studentIdsByName.get(normalizedName)||[]),student.id])}
      const existing=await db.prepare("SELECT student_id AS studentId,record_date AS recordDate,custom_data AS customData FROM student_records WHERE kind=?").bind(kind==="payments"?"payment":"attendance").all<{studentId:number;recordDate:string;customData:string}>(),keys=new Set(existing.results.map(item=>{try{return String(JSON.parse(item.customData).importKey||"")}catch{return ""}}).filter(Boolean));let created=0,skipped=0,invalid=0;const statements=[] as ReturnType<typeof db.prepare>[];
      if(kind==="payments"){
        const memberships=await db.prepare("SELECT student_reference AS studentId,joined_at AS joinedAt FROM group_members").all<{studentId:string;joinedAt:string}>(),offerByTitle=new Map(offers.results.map(item=>{let details:Record<string,unknown>={};try{details=JSON.parse(item.customData||"{}")}catch{}return [item.title.trim().toLowerCase(),{id:item.id,title:item.title,amount:Number(details.amount||0),levels:Number(details.levels||0)}]})),employeeByName=new Map(employees.results.map(item=>[item.name.trim().toLowerCase(),item.id])),priorMainByReceipt=new Map<string,Record<string,unknown>>(),firstEducationalDateByStudent=new Map<number,string>(),educationalPurchasesByStudent=new Map<number,Array<{date:string;levels:number}>>(),membershipDatesByStudent=new Map<number,string[]>(),studentAdjustment=new Map<number,number>(),nonEducationalTypes=new Set(["Books","Make Up","Delivery","Certificate","Placement Test","Test"]);
        for(const student of students.results){let detail:Record<string,unknown>={};try{detail=JSON.parse(student.customData||"{}")}catch{}studentAdjustment.set(student.id,Number(detail.misplacedLevelAdjustment||0))}for(const membership of memberships.results){const studentId=Number(membership.studentId);membershipDatesByStudent.set(studentId,[...(membershipDatesByStudent.get(studentId)||[]),String(membership.joinedAt||"")])}
        for(const item of existing.results){try{const detail=JSON.parse(item.customData||"{}") as Record<string,unknown>;if(detail.isMainPayment){priorMainByReceipt.set(String(detail.main||"").replace(/^#/,""),detail);if(Number(detail.levels||0)>0&&!nonEducationalTypes.has(String(detail.paymentType||""))){const recordDate=String(item.recordDate||"").slice(0,10),levels=Math.max(0,Number(detail.levels||0)-Number(detail.refundedLevels||0));educationalPurchasesByStudent.set(item.studentId,[...(educationalPurchasesByStudent.get(item.studentId)||[]),{date:recordDate,levels}]);if(recordDate&&(!firstEducationalDateByStudent.has(item.studentId)||recordDate<String(firstEducationalDateByStudent.get(item.studentId))))firstEducationalDateByStudent.set(item.studentId,recordDate)}}}catch{}}
        const grouped=new Map<string,Array<{row:Row;index:number;studentId:number}>>();
        for(let index=0;index<rows.length;index++){const row=rows[index],phone=normalizePhone(value(row,"Student Number")),nameMatches=studentIdsByName.get(value(row,"Student Name").toLowerCase())||[],referenceStudent=studentByPhone.get(normalizePhone(value(row,"Reference"))),studentId=studentByPhone.get(phone)||(nameMatches.length===1?nameMatches[0]:undefined)||(referenceStudent&&nameMatches.length&&nameMatches.includes(referenceStudent)?referenceStudent:undefined);if(!studentId){invalid++;continue}const receipt=value(row,"Receipt ID");if(!receipt){invalid++;continue}grouped.set(receipt,[...(grouped.get(receipt)||[]),{row,index,studentId}])}
        for(const entries of grouped.values()){const offerEntry=entries.find(entry=>!value(entry.row,"Payment Type").toLowerCase().includes("rest of money"));if(!offerEntry)continue;const offerTitle=value(offerEntry.row,"Payment Type"),offer=offerByTitle.get(offerTitle.toLowerCase()),type=importedPaymentType(offerTitle);if(Number(offer?.levels||0)<=0||nonEducationalTypes.has(type))continue;const date=dateValue(value(offerEntry.row,"Date")).slice(0,10),current=firstEducationalDateByStudent.get(offerEntry.studentId);if(!current||date<current)firstEducationalDateByStudent.set(offerEntry.studentId,date)}
        const orderedGroups=[...grouped.entries()].sort((a,b)=>{const aOffer=a[1].find(entry=>!value(entry.row,"Payment Type").toLowerCase().includes("rest of money")),bOffer=b[1].find(entry=>!value(entry.row,"Payment Type").toLowerCase().includes("rest of money"));return dateValue(value(aOffer?.row||a[1][0].row,"Date")).localeCompare(dateValue(value(bOffer?.row||b[1][0].row,"Date")))||(aOffer?.index||a[1][0].index)-(bOffer?.index||b[1][0].index)});
        for(const [receipt,entries] of orderedGroups){const sorted=entries.sort((a,b)=>dateValue(value(a.row,"Date")).localeCompare(dateValue(value(b.row,"Date")))||a.index-b.index),offerEntry=sorted.find(entry=>!value(entry.row,"Payment Type").toLowerCase().includes("rest of money")),prior=priorMainByReceipt.get(receipt),rawOffer=offerEntry?value(offerEntry.row,"Payment Type"):String(prior?.offer||"Rest Of Money"),offer=offerByTitle.get(rawOffer.toLowerCase()),baseType=offerEntry?importedPaymentType(rawOffer):String(prior?.paymentType||"Other"),mainDate=offerEntry?dateValue(value(offerEntry.row,"Date")).slice(0,10):"",educational=Boolean(offerEntry&&Number(offer?.levels||0)>0&&!nonEducationalTypes.has(baseType)),priorPurchased=educationalPurchasesByStudent.get(offerEntry?.studentId||0)||[],purchasedBefore=priorPurchased.filter(item=>item.date<mainDate).reduce((sum,item)=>sum+item.levels,0),startedBefore=(membershipDatesByStudent.get(offerEntry?.studentId||0)||[]).filter(date=>date.slice(0,10)<=mainDate).length,remainingBefore=Math.max(0,purchasedBefore-startedBefore-(studentAdjustment.get(offerEntry?.studentId||0)||0)),paymentType=educational?(mainDate===firstEducationalDateByStudent.get(offerEntry!.studentId)?"New Comers":remainingBefore<=1?"Retention":"Renewal"):baseType,total=offer?.amount||Number(prior?.total||0)||sorted.reduce((sum,entry)=>sum+Math.max(0,Number(entry.row.Amount)||0),0),groupPaid=sorted.reduce((sum,entry)=>sum+Math.max(0,Number(entry.row.Amount)||0),0),mainPosition=offerEntry?sorted.indexOf(offerEntry):-1;let runningPaid=0;if(educational)educationalPurchasesByStudent.set(offerEntry!.studentId,[...priorPurchased,{date:mainDate,levels:Number(offer?.levels||0)}]);
          for(let position=0;position<sorted.length;position++){const {row,index,studentId}=sorted[position],amount=Math.max(0,Number(row.Amount)||0),importKey=key("payment",file.name,index+2,receipt);if(keys.has(importKey)){skipped++;continue}const isMainPayment=position===mainPosition,paidBefore=runningPaid,runningAfter=runningPaid+amount;runningPaid=runningAfter;const due=isMainPayment?Math.max(0,total-groupPaid):Math.max(0,total-runningAfter),admin=value(row,"Admin Name"),invoice=`#${receipt}-${String(position+1).padStart(2,"0")}`,detail={importKey,legacyReceiptId:receipt,offerId:offer?.id||prior?.offerId||null,offer:isMainPayment?rawOffer:"Rest Of Money",originalOffer:rawOffer,levels:offer?.levels||prior?.levels||0,paid:amount,netPaid:amount,total:isMainPayment?total:Math.max(0,total-paidBefore),due,method:value(row,"Method"),reference:value(row,"Reference"),paymentType,main:`#${receipt}`,invoice,isMainPayment,isDebtPayment:!isMainPayment,addedById:employeeByName.get(admin.toLowerCase())||null,addedBy:admin||"System",adminPhone:normalizePhone(value(row,"Admin Number")),studentBranch:value(row,"location"),track:value(row,"Track"),importSource:file.name,sourceRow:index+2};statements.push(db.prepare("INSERT INTO student_records (student_id,kind,record_date,status,notes,custom_data) VALUES (?,'payment',?,?, '',?)").bind(studentId,dateValue(value(row,"Date")),due>0&&isMainPayment?"Partial":"Paid",JSON.stringify(detail)));keys.add(importKey);created++}
        }
      }else for(let index=0;index<rows.length;index++){const row=rows[index],phone=normalizePhone(value(row,"Mobile")),studentId=studentByPhone.get(phone),importKey=key("absence",dateValue(value(row,"Date")),phone,value(row,"Group"),value(row,"Session No."));if(!studentId){invalid++;continue}if(keys.has(importKey)){skipped++;continue}const groupId=findId(groups.results,value(row,"Group")),detail={importKey,groupId,groupTitle:value(row,"Group"),sessionNumber:Number(row["Session No."])||0,time:value(row,"Time"),branch:value(row,"Branch"),level:value(row,"Level"),importSource:file.name};statements.push(db.prepare("INSERT INTO student_records (student_id,kind,record_date,status,notes,custom_data) VALUES (?,'attendance',?,'Absent','',?)").bind(studentId,dateValue(value(row,"Date")),JSON.stringify(detail)));keys.add(importKey);created++}
      for(let i=0;i<statements.length;i+=80)await db.batch(statements.slice(i,i+80));return Response.json({ok:true,created,skipped,invalid,total:rows.length});
    }
    const records=rows.map((row,index)=>{const mobile=normalizePhone(value(row,"Mobile 1")),createdAt=dateValue(value(row,"DateTime")).replace(/^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*/,"$1"),rawHistory=kind==="callCenter"&&value(row,"__EMPTY")?value(row,"__EMPTY"):value(row,"History"),events=history(rawHistory),result=callResultFromNote(events[0]?.notes,value(row,"Call Result","Last Call Action")),studentStatus=kind==="callCenter"?value(row,"History","Not Reg / Reg / Paid","Student Status Now"):value(row,"Not Reg / Reg / Paid","Student Status Now"),common={fullName:value(row,"Name")||`عميل ${mobile}`,primaryPhone:mobile,secondaryPhone:normalizePhone(value(row,"Mobile 2")),source:value(row,"Source"),interest:value(row,"Course","Track"),assignedEmployeeId:findId(employees.results,value(row,"Agent","Last Call By","Last Call Action")),branchId:findId(branches.results,value(row,"Branch")),createdAt,result,notes:events[0]?.notes||"",sheetRow:index+2,importSource:file.name,customData:{job:value(row,"Job"),gender:value(row,"Gender"),age:value(row,"Age"),segment:value(row,"Segment"),nationality:value(row,"Nationality"),country:value(row,"Country"),governorate:value(row,"Government"),area:value(row,"Region"),history:events,studentStatusNow:studentStatus,sourceStatus:value(row,"Status"),reason:value(row,"Reason","Reason Inactive")}};return kind==="received"?{phone:mobile,callAt:createdAt,result,notes:events[0]?.notes||"",assignedEmployeeId:common.assignedEmployeeId,branchId:common.branchId,sheetRow:index+2,importKey:key("call-history",mobile,createdAt.slice(0,16)),importSource:file.name,customData:{...common.customData,fullName:common.fullName,name:common.fullName,secondaryPhone:common.secondaryPhone,mobile2:common.secondaryPhone,source:common.source,course:value(row,"Course"),track:value(row,"Track"),interest:common.interest,agent:value(row,"Agent","Last Call By","Last Call Action"),branch:value(row,"Branch"),status:value(row,"Status"),reason:value(row,"Reason"),product:value(row,"Product"),prospect:value(row,"Prospect"),lastCallBy:value(row,"Last Call By"),studentStatus,callResultRaw:value(row,"Call Result")}}:{...common,status:"new",finalStatus:studentStatus||"Not Yet",importKey:key(kind,mobile,createdAt,index+2),calls:events.map((event,eventIndex)=>({direction:"outgoing",result:callResultFromNote(event.notes,result),callAt:event.at,notes:event.notes,assignedEmployeeId:findId(employees.results,event.employee),customData:{importKey:key("call-history",mobile,String(event.at).slice(0,16)),historyIndex:eventIndex}}))}}).filter(record=>normalizePhone(String(kind==="received"?(record as Row).phone:(record as Row).primaryPhone)).length>=8);
    const existingLeads=await db.prepare("SELECT id,normalized_phone AS phone FROM leads").all<{id:number;phone:string}>(),leadPhones=new Set(existingLeads.results.map(item=>item.phone)),existingCalls=await db.prepare("SELECT json_extract(custom_data,'$.importKey') AS importKey FROM call_records WHERE json_extract(custom_data,'$.importKey') IS NOT NULL").all<{importKey:string}>(),callKeys=new Set(existingCalls.results.map(item=>item.importKey));let created=0,skipped=0;const leadStatements=[] as ReturnType<typeof db.prepare>[];
    if(kind==="leads")for(const record of records){const phone=normalizePhone(String((record as Row).primaryPhone||""));if(leadPhones.has(phone))continue;const detail={...((record as Row).customData as Row),importKey:(record as Row).importKey,importSource:file.name,finalStatus:(record as Row).finalStatus};leadStatements.push(db.prepare("INSERT INTO leads (full_name,primary_phone,normalized_phone,secondary_phone,source,interest,status,assigned_employee_id,branch_id,notes,custom_data,created_at,updated_at) VALUES (?,?,?,?,?,?,'new',?,?,?,?,?,?)").bind((record as Row).fullName,(record as Row).primaryPhone,phone,(record as Row).secondaryPhone,(record as Row).source,(record as Row).interest,(record as Row).assignedEmployeeId,(record as Row).branchId,(record as Row).notes,JSON.stringify(detail),(record as Row).createdAt,(record as Row).createdAt));leadPhones.add(phone)}
    for(let i=0;i<leadStatements.length;i+=80)await db.batch(leadStatements.slice(i,i+80));created+=leadStatements.length;
    const callInputs=records.flatMap((record)=>{if(kind==="callCenter"){const sourceHistory=Array.isArray(((record as Row).customData as Row)?.history)?(((record as Row).customData as Row).history as Row[]):[],byMinute=new Map<string,Row>();for(const event of sourceHistory){const minute=String(event.at||"").slice(0,16);if(minute&&!byMinute.has(minute))byMinute.set(minute,event)}const events=[...byMinute.values()].sort((a,b)=>String(a.at).localeCompare(String(b.at))),originalMinute=String((record as Row).createdAt||"").slice(0,16),received=String(((record as Row).customData as Row)?.studentStatusNow||"").toLowerCase()==="received";return events.map((event,index)=>{const eventMinute=String(event.at||"").slice(0,16),direction=received&&eventMinute===originalMinute?"incoming":"outgoing",sequence=received&&direction==="outgoing"?Math.max(1,index):index||undefined;return {...record,callAt:event.at,notes:event.notes,assignedEmployeeId:findId(employees.results,String(event.employee||""))||Number((record as Row).assignedEmployeeId)||null,result:callResultFromNote(event.notes,(record as Row).result),historyImportKey:key("call-history",(record as Row).primaryPhone,eventMinute),direction,...(received&&direction==="outgoing"?{inboundFollowupSequence:sequence}:{followupSequence:sequence})}})}if(kind!=="leads")return [record as Row];const sourceHistory=Array.isArray(((record as Row).customData as Row)?.history)?(((record as Row).customData as Row).history as Row[]):[],byMinute=new Map<string,Row>();for(const event of sourceHistory){const minute=String(event.at||"").slice(0,16);if(minute&&!byMinute.has(minute))byMinute.set(minute,event)}const events=[...byMinute.values()].sort((a,b)=>String(a.at).localeCompare(String(b.at)));return events.map((event,index)=>({...record,callAt:event.at,notes:event.notes,assignedEmployeeId:findId(employees.results,String(event.employee||""))||Number((record as Row).assignedEmployeeId)||null,result:index===events.length-1?(record as Row).result:callResultFromNote(event.notes),historyImportKey:key("call-history",(record as Row).primaryPhone,String(event.at).slice(0,16)),followupSequence:index||undefined}))});
    const callStatements=[] as ReturnType<typeof db.prepare>[];for(const record of callInputs){const phone=String(kind==="received"?(record as Row).phone:(record as Row).primaryPhone),phoneKey=normalizePhone(phone),callAt=String((record as Row).callAt||(record as Row).createdAt),importKey=String((record as Row).historyImportKey||(kind==="received"?(record as Row).importKey:key("call-history",phoneKey,callAt.slice(0,16))));if(callKeys.has(importKey)){skipped++;continue}const direction=String((record as Row).direction||(kind==="received"?"incoming":"outgoing")),detail={...((record as Row).customData as Row),importKey,importSource:file.name,finalStatus:(record as Row).finalStatus||"Not Yet",...((record as Row).followupSequence?{followupSequence:(record as Row).followupSequence}:{}),...((record as Row).inboundFollowupSequence?{inboundFollowupSequence:(record as Row).inboundFollowupSequence,inboundFollowupPhone:phoneKey}:{}),callSource:direction==="incoming"?"received":"leads"},result=String((record as Row).result||"Answered"),employeeId=Number((record as Row).assignedEmployeeId)||null,branchId=Number((record as Row).branchId)||null,notes=String((record as Row).notes||"");callStatements.push(db.prepare("INSERT INTO call_records (lead_id,phone,direction,result,assigned_employee_id,branch_id,call_at,notes,custom_data,created_at) VALUES ((SELECT id FROM leads WHERE normalized_phone=? ORDER BY id LIMIT 1),?,?,?,?,?,?,?,?,?)").bind(phoneKey,phone,direction,result,employeeId,branchId,callAt,notes,JSON.stringify(detail),callAt));callKeys.add(importKey)}for(let i=0;i<callStatements.length;i+=80)await db.batch(callStatements.slice(i,i+80));created+=callStatements.length;return Response.json({ok:true,created,skipped,invalid:rows.length-records.length,total:rows.length});
  }catch(error){console.error(error);return Response.json({error:error instanceof Error?error.message:"تعذر استيراد الملف"},{status:500})}
}
